- bower.json
@dlockhart : these are initial version updates to pick up recent typography changes for C12.  Besides vui-typography, it also includes vui-input and jquery-vui-collapsible-section version updates since those components needed a couple small tweaks as a result of removing variables and changing the typography mixins.
> Initial version updates to pick up recent C12 typography.

- package.json
- src/bsi.scss
- src/text-image-link.scss
@dbatiste: thoughts? This control currently has a copy of our link styles (colour mostly) -- it should really reference them from here. If this works, I'll port this over to the c12 branch and adapt it accordingly. I'll also do something similar for html-block.
> outputting classes for text-image-link control

- package.json
The npm project Uglify on windows throws errors when trying to minify css. Updated project to use the vastly more popular clean-css and uglify-js projects for minifying js and css code.
> Updated build pipeline to use clean-css and uglify-js over uglify

- bower.json
- package.json
- src/bsi.html
This PR adds `bsi.html` and `vulcanize` build step.  Eventually the `unresolved` JS will be replaced once we are including components.
@dlockhart : be awesome if you could take look.
> Add bsi.html (with placeholder).

- README.md
Itty bitty PR. Omitting the trailing slash causes things to not work, which is less than ideal.
> Add note about trailing slash to readme

- src/page.scss
This is a result of work on the announcements page to make it look better on mobile.  We found the padding to be a bit excessive on smaller screens.
I'm using EMs here which I personally like for media queries but I could also change it to px if that's what is preferred.
Jeff and I discussed this and would like to further improve it in the not too distant future, to work with our overall grid design - but this is still helpful now.
@dlockhart
> Us70869 page padding on smaller viewports

- src/icons.scss
- src/vui.scss
@dbatiste, @njostonehouse, @capajon 
With the new Daylight icons, the size of `bsi.min.css` has gotten out of control:
- before Daylight icons: 137Kb
- with Daylight icons: 335Kb
- with no icons as all (after this PR): 92Kb
As you can see, the main problem is that we're including the CSS to use each icon as a background image by class-name. The monolith only uses those class names in a couple places, and even then has a way to fall back. So I'd like to remove this altogether with Daylight.
Corresponding PR in ILP:
https://git.dev.d2l/projects/CORE/repos/lp/pull-requests/2660/overview
A few UMD-based FRAs [are referencing these class names](http://search.dev.d2l/source/search?q=%22vui-icon%22&defs=&refs=&path=&hist=&type=&project=LSOne), and I've reached out to them to try and get them to …
> not including all the VUI icons CSS classnames

- bower.json
- bsi-style.html
- bsi.html
- button-menu.html
- button-split.html
- button.html
- collapse-pane.html
- headings.html
- htmlblock.html
- htmleditor.html
- package.json
- src/container-icon-link.scss
- src/context-menu.scss
- src/deprecated/button.scss
- src/deprecated/icons.scss
- src/deprecated/link.scss
- src/deprecated/offscreen.scss
- src/dialog.scss
- src/file-link.scss
- src/floating-container.scss
- src/grid.scss
- src/link.scss
- src/offscreen.scss
- src/page-two-column.scss
- src/page-two-panel-selector.scss
- src/page.scss
- src/text-image-link.scss
- src/vui.scss
@dbatiste, @njostonehouse, @capajon, @ryantmer 
First set of a series of changes to BSI that will upgrade it to use the `d2l-*` version of our UI components instead of `vui-*`. Accompanying this will be a change to the ILP-Core to pick up some of the new web component custom elements (e.g. `<button is="d2l-button">` instead of `<button is="vui-button">`) and class names.
This is also the beginning of removing our dependency on those `#bsi-wc` branches some of the components needed in order to still reference the old Sass mixins until they were upgraded to web components themselves.
> VUI to D2L 1.0

- button.html
This change effectively flips the LTR right margin on buttons when inside of legacy right-aligned layout.  Corresponding is the RTL equivalent.  Without this change there is a 0.75rem right margin that bumps the button in, causing the right-most button to not be aligned with the containing edge.
> Fix legacy layout of right aligned buttons.

- bower.json
This version isn't available quite yet, but Travis is being incredibly slow, so CI is many minutes to start anyway... by the time it does, this version should be up.
> Update d2l-my-courses to v0.8.1

- src/context-menu.scss
@dbatiste FYI, this comes with a corresponding PR in the LMS to no longer render the icons
> removing support for context-menu icons

- .travis.yml
- headings.html
- package.json
FYI @njostonehouse, @dbatiste, @capajon 
Using `normal` line-height instead of `100%` to avoid clipping of extenders (e.g. "y" and "g") in certain browsers. In general I think we should always be using `normal` when the desired effect is for the text to be "as short as possible". I'm going to adjust a few places in the LMS as well that are doing this.
Reference: http://stackoverflow.com/questions/25470084/minimum-line-height-to-ensure-text-is-not-cut-off
> line height fix

- src/page-two-panel-selector.scss
@dlockhart This is related to the "useResponsiveCollapseLayout" changes in the LE that we were holding off putting in 10.6.6.
> Two panel responsive collapsing columns pass one

- bower.json
- src/dialog.scss
- src/vui.scss
@njostonehouse @dlockhart 
The issue this is solving is legacy dialogs opening with a height of 1px on the content.  This happened because of some new responsive rules that set heights to 100%.  The JS tries to dynamically set the height based on a few (confusing) things - and that CSS messes it up.
The fix ended up being fairly simple, just using flexbox basically.  I'll note that I tried a lot of other things first in the LE, mostly with how the javascript worked, but it is really confusing and never quite worked well in all situations.  Flexbox seems to take care of things so I'm happy enough with it.  I don't think dialogs are any better/worse overall with this change (but mostly work now so that's good).
> Fix legacy dialogs on mobile

- bower.json
Patch version 2 was a typo when I released Typography 4.3, but I don't think it will create any problems to be missing versions .0 and .1.
> DE23046: Bump typography version for small and standard font classes.

- src/page-loading/page-loading.js
@dbatiste look OK? Basically only waiting for the WC ready event before fading in the page. I still want to do a lot of work to navigation so that it progressively loads while still showing _something_, but that's separate.
> no longer waiting for the "nav ready" event to fade the page in

- src/page-loading/page-loading.js
@dbatiste @omsmith The main use case for this right now is so that we can grab this data when it's ready and send it off to AppDynamics.
> firing an event when perf measures are ready so we can do things with them

- .eslintrc
- src/page-loading/page-loading.js
Simplifying how the page-loading code works:
- since navigation is now not a dependency on fading the page in, removing all references to it
- renaming the `domContentLoaded` measure to `domContentLoadedHandlers` to more accurately reflect its purpose
- logging the performance measures in the `onload` callback, since waiting for the `pageReady` isn't necessary
- no longer measuring the `webComponentsReady` event since it always corresponds to the `page.display` event anyway, and in cases where the polyfill wasn't required (Chrome), it wasn't getting logged at all.
@dbatiste thoughts?
> Page loading tweaks

- src/bsi.scss
- src/navigation/common.scss
- src/navigation/index.scss
- src/navigation/no-login.scss
- src/navigation/shadow.scss
@dbatiste This is the required CSS from the client-side navigation just to render the "no login" version of the navbar, which is going to be the first server-side rendering experiment (PR in platformTools to follow).
> moving over the “no login” navigation and shared components

- src/bsi.scss
- src/page-loading/page-loading.js
- src/page-loading/page-loading.scss
@dbatiste look OK? This CSS along with the `d2l-page-loading` class is no longer needed now that we're not waiting for the navigation to load before fading the page in. Instead, we can rely on the `unresolved` attribute on the body, which Polymer will remove for us and supply the opacity CSS.
I'll make a PR in platformTools to remove the class names and update BSI.
> remove page-loading fade-in

- bower.json
This isn't really needed in the next release. Only a minor performance gain, and doesn't really affect page load times overall
> Bump button-group

- src/dialog.scss
[see](https://trello.com/c/ozOZHi45/122-bug-ios-prod-can-t-scroll-versioning-list) for the additional description
> Fix scrolling inside <dialog-iframe> for mobile version of Safari

- src/navigation/header.scss
It seems that we don't have to add another css class for it since the reduced title is applied whenever a title is present at header-logo-area.
> reduce title size to 25px

- src/event.polyfill.js
- src/index.js
https://github.com/webcomponents/webcomponentsjs/blob/9387b123767397584698d9a403aefcc640572179/src/WebComponents/dom.js#L80
Fixes IE11 (Edge?) not reporting d2l.page.display when daylight is off
> Add WebComponent's CustomEvent polyfill

- jsonp-imports.js
give them a .js extension instead which makes more sense anyway
https://github.com/Brightspace/webcomponentsjs/pull/1
> "jsonp" imports for IE should be getting gzipped.

- src/navigation/highlight-icon.scss
The bar and text were getting the active color when menus were open, but the icon wasn't. This fixes DE23968.
> setting color of icon when active in addition to text

- bower.json
- bsi.html
Acceptance Criteria:
d2l-alert lives independently from d2l-my-courses-ui as a Polymer web component
d2l-my-courses-ui is refactored to use d2l-alert as a dependency
nothing breaks
d2l-alert now lives here: https://github.com/Brightspace/alert
Intention is to someday move it to BrightspaceUI
> US81437: d2l-alert factored into its own component

- bower.json
prevents problems arising from mismatched d2l-alert states!
@omsmith
> bump d2l-my-courses to 0.25.0

- src/navigation/mobile-menu.scss
Firefox was choosing to use left:0 over right: 0 with RTL on.
> Fixing positioning of mobile menu in rtl on firefox

- src/navigation/main.scss
This change adds `flex-wrap: wrap` CSS for nav links flex container so that browsers (namely Safari on iOS) can measure dimensions unsquished (yes, that is a technical term... ;)  ).  
With the exception of IE, always allowing wrapping works fine because we hide links that won't fit before the browser has had a chance to wrap them.  When chomping in IE (ex. via resizing), the links wrap and then disappear, resulting in bumping effect.  To remedy this, we will still apply `flex-wrap: nowrap` after measurements are made.
There will be a corresponding PR in LMS to add/remove the `data-unmeasured` attribute.  Alternatively, we may be able to piggyback on existing `data-loading` attribute.
> Provide CSS for unmeasured nav items for iOS Safari chomping.

- src/navigation/mobile-menu.scss
This change is being made to prevent tabbing to mobile flyout children when in the closed state.
> Set display:none for mobile nav menu in closed state

- bower.json
Updating d2l-icons to v3.1.0, which contains the new html-editor icon for the TinyMCE a11ychecker plugin.
> US81575 - Adding html-editor icon for TinyMCE a11ychecker plugin

- package.json
Was only ever matching the first file, meaning we were only getting bsi.html.js, not the rest of them. Introduced in https://github.com/Brightspace/brightspace-integration/commit/d16d58cbd21dee24c645c24829b079035fee6117 to fix this exact problem, seemingly.
> Fix jsonp match

- .gitignore
Since we're committing bower_components on this branch, this will ensure that changes to bower_components aren't missed - and, perhaps just as importantly, will make it blatantly obvious if more changes occurred than intended.
> Don't ignore bower_components on v10.6.12

- package.json
This works (for me, at least) on Windows and WSL, would love for someone to give it a try on Linux and if it works there too lets merge it in. I'd love to get me some bsi.html.js in my dist folder again :)
> Fix jsonpify-imports script to work on all envs

- src/page-loading/page-loading.js
- src/page-loading/web-components-ready.js
Adding some new user timings:
- "server": captures time spent on the server processing the request (fetchStart -> responseStart)
- "download": time spent downloading the response (responseStart -> responseEnd)
- "visible": very similar to "display" (and may replace it) except it excludes the time spent on the server and downloading (responseEnd -> webComponentReady). This helps us isolate client-side performance improvements from variation in server time / download time.
In testing, I found that generally: display = server + download + visible. That to me indicates that there isn't much overlap between those events -- i.e. that the browser isn't doing a lot of processing of the document until it's fully downloaded. That may change for large documents, but it's what I was seeing.
I'm going …
> new timings

- src/navigation/admin-menu.scss
- src/navigation/common.scss
- src/navigation/divider.scss
- src/navigation/header-course.scss
- src/navigation/header.scss
- src/navigation/highlight-icon.scss
- src/navigation/main.scss
- src/navigation/mobile-menu.scss
- src/navigation/personal-menu.scss
- src/navigation/shadow.scss
Confirmed this results in the same output CSS by doing a side-by-side diff.
> vendor prefixes aren’t needed as they’re added automatically by autoprefixer

- .eslintrc
- src/index.js
- src/page-loading/timing-debug.js
- src/page.scss
@dbatiste, @omsmith What do you guys think? This would let us not need to keep opening up the console to get at the timing variable values when doing manual performance tests... which will be especially handy in Edge since the console leaks like a sieve.
How it works: you just need to put this in the URL bar and visit any page `&timingdebug=1`. That'll store in session storage that you want to see the "d2l.page.visible" timing variable output to the page for every page visit. To stop showing it, either add `&timingdebug=0` or remove it manually from session storage.
It looks like this, just kind of floating there:
> making the “d2l.page.visible” timing visible on the page if asked for it

- postcss.config.json
I _think_ this is what we want.
To give an idea of the raw size change:
```
bsi.css          111KB -> 97KB (-12.6%)
bsi.min.css      89KB -> 79KB (-11.2%)
```
> Update autoprofix config to reflect current browser support.

- src/navigation/common.scss
Demonstration of the bug:
Width of all the elements in the navbar at this viewport size from left to right:
30 (hamburger) + 42 (separator) + 260 (logo) + 30 (spacing) + 40 (course menu) + 42 (separator) + 160 (notifications) + 42 (separator) + 42 (personal menu) + gutters (2.44% = ~33) - 7 (negative margins on the logo) = **714px**.
So that means that at ~714px, with a logo that takes up the full max-width of 260, the logo starts to get cut off -- and it does. So the responsive rule to hide the logo should kick in at 714 instead of 670.
> DE24640: adjusting the responsive rules so the logo doesn't get cut off

- bower.json
- sass/deprecated/link.scss
- sass/html-block.scss
- sass/links.scss
I'll be switching the LMS over to use the "d2l-link" CSS class instead of the web component, as the performance gains are too significant right now to ignore.
This change pulls in the latest version of `d2l-link` -- which has Sass mixins now -- and applies the mixins to the `.d2l-link` CSS class and `.vui-link` class (for backwards compatibility with old FRAs). It also applies it inside HTML blocks for user-authored content.
> reintroducing d2l-link class

- bower.json
Removes usage of `d2l-siren-parser-ui`, as well as a loading spinner fix. Major version bump to make it more semver-y, not actually expecting any truly breaking changes.
> Bump banner overlay version

- sass/button-menu.scss
@dbatiste Ended up being a specificity issue with the reset stylesheet's `:hover` effect.
From the reset:
```
a, a:hover {
color: blue;
}
```
Original CSS for button-menu:
```
.bsi-button-menu {
color: red;
}
```
`a:hover` ends up being more specific than `.bsi-button-menu`, so it wins. Must have been slightly different when this was coming from the web component style include -- probably only in shady DOM though.
> fixing normal text colour on-hover

- bower.json
1.0.1 breaks in Safari < 10.1 and IE, and 1.0.2 breaks in everything so lets make sure we get 1.0.3 at a minimum
> Move to latest banner overlay release

- d2l-table.html
Pre-daylight, MVC grid cell alignment was "top" by default. The Daylight tables have a default "middle" vertical alignment, which caused a few places that were depending on top to manually start overriding it.
This puts the alignment back to "top" for MVC grids only. Legacy grids were always middle, so no need to impact them.
Corresponding change coming in the LMS to add the "d2l-grid-mvc" class and upgrade BSI.
> keeping MVC grid cell vertical alignment consistent with pre-daylight

- sass/navigation/admin-menu.scss
- sass/navigation/common.scss
- sass/navigation/course-menu.scss
- sass/navigation/divider.scss
- sass/navigation/header-course.scss
- sass/navigation/header.scss
- sass/navigation/main.scss
- sass/navigation/mobile-menu.scss
- sass/navigation/notifications.scss
- sass/navigation/personal-menu.scss
Second go at this, now with less margin changes and other issues, I hope. :)
I still used margin-right and some RTL styles on a few elements because the combination of them and sharing of styles between the mobile menu and main nav is a bit tricky and I wanted to go with something I was more confident in.  But most margins are like what they were before.  I wish the mobile menu and nav styles were separated more and only used vars and mixins to share sometimes.
I tested in all the combinations of nav settings I am aware of (more or less!) and RTL and things seem.. okay so far.  I will check again tomorrow.
I also tried to break the branding flag less than I did before, but I am changing lots of stuff that effects both on/off for it.  So I assume lots is broken before.  Actually I just …
> New breakpoint design for navigation

- src/context-menu.scss
upgrading node-sass to attempt to fix Travis failures
fixing right margins on context-menus
Original PR:
https://github.com/Brightspace/brightspace-integration/pull/575
> port_fixes_for_DE26710_DE26711

- table.html
defaulting table cell alignment to "top" for MVC grids
Original PR: #579
> port_fixes_for_DE26713_DE26712

- sass/dialog.scss
The selector for positioning properties was incorrectly defined.  The background position for the icon was also not needed, since it is centered.
> DE25007 - Fix dialog close button rtl position.

- bower.json
This new `d2l-scroll-spy` version is needed to properly support partial rendering of the scroll-spy import so that `registerPoint` is not called too early.
> DE27540 - Update to latest d2l-scroll-spy to include ready event.

- js/page-loading/web-components-ready.js
I was finally able to reproduce that mysterious `Cannot read property ‘measure’ of undefined” JavaScript error locally on my machine. Previously we'd only seen it in test automation runs, and sporadically.
What causes it is a very slow CPU. I reproduced it in Chrome by throttling the CPU down to "20x slower" in Chrome dev tools. That seems to cause the web component import code (and this code in `web-components-ready.js`) to actually run _before_ the `D2L.Performance` library is initialized in `bsi.js`. This makes sense in Chrome, since it would treat an import with the same priority (or higher) than a JavaScript file, and `bsi.js` is loaded at the bottom of the page.
Beyond just protecting things here with a safety check, I'm not sure what a better solution might be for these types of …
> safety check around performance measuring

- bower.json
- bsi.html
- js/index.js
- js/polyfill/Array.prototype.includes.js
Not currently an issue due to how things are structured, but I forgot to move this polyfill over [from d2l-my-courses](https://github.com/Brightspace/d2l-my-courses-ui/blob/master/polyfill/Array.prototype.includes.js) when I restructured things. Required for IE11 because of course it is.
(I'll remove it from My Courses once this is merged)
> Add Array.prototype.includes polyfill for d2l-fetch-simple-cache

- build-email-icons.js
- package.json
Convert a subset of icons used for notification emails to .png and add to new folder.
> Add build step for email icons

- bower.json
1.11.1 breaks table's sticky buttons. Will investigate further and unlock this once we have a fix for table.
> Forcing on Polymer 1.11.0

- bower.json
- bsi.html
- js/index.js
- package.json
Part 2 of this change.
Part 3 is in the monolith, where the few places that reference `BSI.Intl` need to switch to use the global `d2lIntl` object.
> Use intl import

- js/index.js
Missed the fact that Daylight-OFF references the same `d2lIntl` object. So renaming to match corresponding change to master (Daylight) branch.
> renaming BSI.Intl to d2lIntl

- bower.json
- d2l-table.html
This will go with a corresponding pull request and change to the monolith that aligns its usage of `d2l-table` with the breaking changes introduced for the hybrid version.
> upgrading to hybrid version of d2l-table

- bower-locker.bower.json
- bower.json
Picks up Firefox support for Daylight radios & checkboxes
> upgrading to vui-input 2.0.4

- bower-locker.bower.json
- bower.json
- js/index.js
I'm pulling this out of BSI (and the associated use in the LMS), since it's no longer being used to send telemetry data anywhere. This will eventually get replaced with a better telemetry solution, but in the meantime there's no point in including it and it's preventing me from making some changes to how `D2LPerformanceMeasure` works.
> removing inclusion of telemetry

- js/page-loading/performance-timings.js
@svanherk @dbatiste Thoughts?
This switches the start time of the `webComponentsReady` measure to the beginning of the original navigation. Previously it used the `responseEnd`, or when it received the last byte of the response. This should bring the number in-line with the paint timings and TTI measures so that they're all comparable.
The downside to this approach is that network lookup, server processing and response download all have an impact on the WCR event. But they also impact the paint and TTI timings. To give us a bit more information, I've added the `d2l.page.timeToClient` measure, which tries to capture the time it took from `navigationStart` to `responseEnd`.
> adjusting the webComponentsReady measure to start at the time origin

- js/d2l-fastdom.js
- js/index.js
- js/page-loading/timing-debug.js
- package-lock.json
- package.json
- rollup.config.js
Revisited this from a long while back. Output seems more obviously correct, but haven't tested locally yet.
bsi.js is larger since we were already minifying as a transform in the browserify bundle.
| File | Master | Rollup (% Master) | Rollup & Uglify3 (% Master) |
| ----- | --------- | -------- | ---------------------- |
| bsi.js | 24683 | 40231 (163) | 40231 (163) | 
| bsi.js.gz | 7027 | 9402 (134) | 9402 (134) |
| bsi.min.js | 24174 | 21597 (89) | 21398 (89) |
| bsi.min.js.gz | 6927 | 6318 (91) | 6299 (91) |
> Smaller bsijs bundle

- bower-locker.bower.json
- bower.json
This PR updates `<d2l-table>` to v1.4.0, which fixes the extra white-space atop tables in Edge/IE and restores the sticky scroll buttons to their former glory in all the browsers (and under Shadow DOM). There is one known regression in Edge16 RTL that is [being tracked here](https://github.com/BrightspaceUI/table/issues/159).
[Screenshots demoing it in the LMS](https://d2lmail-my.sharepoint.com/:f:/g/personal/ppaskaris_desire2learn_com/EswaC76oJrJDh7BxlaRZFI8Br88_GXXAEFNJJW7rJn_BXg).
> Update d2l-table to v1.4.0

- sass/homepages/homepages.scss
I think better fix is that always have top margin on each widget. I have tried again with displaying banner and Org title, both looked fine.
The problem with previous change is that when the panel is empty, it still has top-margin that is not needed any more.
> DE30092-always add top margin to each widget

- sass/html-block.scss
This is required for the overflow properties on 'd2l-htmlblock' to kick in properly.
> Add relative position to d2l-htmlblock-untrusted elements

- js/index.js
- js/polyfill/Array.prototype.findIndex.js
@omsmith @ChrisKraljevicD2L We'll most likely try and get this merged into master tonight and deployed to the LMS.
But wanted to give you a heads up in case it causes any issues or in case there is a better way to handle this. I just followed what had been done to polyfill `Array.includes`.
This is required for some recent changes to add domain whitelisting to `d2l-fetch-siren-entity-behavior`. That lib was updated in BSI yesterday and is required for d2l-rubric.
> polyfill findIndex for IE11

- .travis.yml
According to the [Travis docs](https://docs.travis-ci.com/user/customizing-the-build/#Breaking-the-Build), a failure in `after_success` will not actually fail the build. This means that the deployment step failing would not actually fail the job, resulting in an erroneous success state.
> Fail when deployment fails

- bower-locker.bower.json
- bower.json
- sass/deprecated/breadcrumbs.scss
- sass/vui.scss
I'm going to pull all the ancient `vui-` stuff directly into BSI, starting here with breadcrumbs.
My reasoning is that most of these will become full-fledged Brightspace UI components at some point (maybe), but in the meantime the old `vui-` repos are still referencing colors and icons and such... and they're so old that they're starting to break. And most of them don't build anymore to even be able to go in and update them.
> Remove vui-breadcrumbs

- bower-locker.bower.json
- bower.json
This version introduces the usage of the `d2l-enrollments` component(s), which replace the now-defunct component(s) from the `1.x-hybrid-components` repo.
The repository that burns twice as bright burns half as long.
> US98453 Update My Courses

- bower.json
The 3.1.2 release of `d2l-tile` actually contained a breaking change to `d2l-card`. Until we sort that out, decrease (un-bump?) the `d2l-tile` version here.
> Rollback d2l-tile

- bower-locker.bower.json
- bower.json
- polymer.json
- web-components/d2l-my-dashboards.html
After this I believe there are two things left to do.
1. Publish a release
2. Update the LMS to use the latest BSI
Seems like I only need to updated `daylight-polymer-1` since we do not use polymer-2 or polymer-3? is there a reason why there are not many updates to the `daylight-off-polymer-X` ones?
> US97007 - Publish d2l-my-dashboard into BSI

- package-lock.json
- package.json
Technically these aren't needed by Polymer 1. `babel-helpers` are needed by both Polymer 2 and 3 (for non-ES6 browsers) and `esm-amd-loader` is needed by Polymer 3.
The reason we need them here is because of the way BSI assets are verified by the LE's integration tests. It assumes that all BSI assets will be present on the CDN for all the different variations of BSI. Since we're trying to get to a single BSI version anyway, I don't really want to add the concept of certain things only being needed for particular Polymer versions into the LE. It's easier to just put these here.
> adding babel-helpers and esm-amd-loader

- sass/navigation/header.scss
This fixes [this issue in d2l-navigation](https://github.com/BrightspaceUI/navigation/issues/6).
Now that navigation is using web components, when shadow DOM is enabled we can't reference their internal CSS classes like `.d2l-navigation-header-container` -- they're protected by scoping.
We'll have to be diligent of issues like this as we convert more of navigation over to WCs.
> fixes CSS not getting applied when shadow DOM is enabled

- sass/navigation/logo.scss
- sass/navigation/notifications.scss
- web-components/navigation-icons.html
Removing styles removed in
- https://git.dev.d2l/projects/CORE/repos/platformtools/pull-requests/2736/overview
- https://git.dev.d2l/projects/CORE/repos/platformtools/pull-requests/2656/overview
- https://git.dev.d2l/projects/CORE/repos/platformtools/pull-requests/2653/overview
`d2l-navigation-s-button-highlight`
Still used in http://search.dev.d2l/source/xref/Lms/platformTools/navbars/D2L.PlatformTools.Navbars/Web/Desktop/Rendering/Views/Daylight/LinkHighlightIcon.Renderer.cs
`d2l-navigation-s-logo-wrapper`
Removed
`d2l-navigation-s-logo-link`
Removed
`d2l-navigation-s-highlight-bar`
Still used in http://search.dev.d2l/source/xref/Lms/platformTools/navbars/D2L.PlatformTools.Navbars/Web/Desktop/Rendering/Views/Daylight/LinkHighlightIcon.Renderer.cs …
> Removing unneeded styling due to new buttons and links from d2l-navigation

- sass/navigation/main.scss
This was bothering me for a while. :)
I think this happened when our "..." [menus increased in size](https://github.com/BrightspaceUI/dropdown/pull/133/files) from `34px` to match the size of all our other menus at `42px`. The space that we leave in the navbar for this menu didn't increase accordingly.
Looks like we were leaving ~`11px` previously (45-36) -- I've adjusted it to be `10px`.
> increasing the space we leave for the nav admin menu

- js/d2l-web-components-ready.js
- js/index.js
- js/polyfills.js
- test/web-components-ready.js
I don't intend to merge this until after branching on Friday.
Currently we have a bunch of code waiting for the `WebComponentsReady` event, mostly to defer but sometimes to ensure that all the polyfills are there before using them. These places have ugly bits because `WebComponentsReady` may have already fired, so they need to check `d2lWCRDispatched` and conditionally add a listener or execute right away. That sucks.
Additionally, in Polymer 3 our web component bundles are going to load asynchronously. So just because `WebComponentsReady` has fired doesn't mean that our bundles have loaded, only that the polyfills are there. So we need a nice mechanism that knows when both have occurred in Polymer 3 land.
Enter: this pull request.
It's loosely modelled after …
> Queue for callbacks interested in being called after WCR

- js/d2l-web-components-ready.js
- js/index.js
- package-lock.json
- test/web-components-ready.js
- web-components/bsi.html
Applying the same treatment as we use in Polymer 3-land of waiting for both the `WebComponentsReady` event AND the end of the imports file to be reached.
People are noticing JS errors on Spark, mostly involving `d2lIntl` not being defined. It's a timing issue that's very tricky to reproduce. I was able to get Safari to exhibit it if I loaded the page and then hit back very quickly. Under this circumstance, `window.WebComponents` doesn't exist for some reason -- even though the polyfill file is first and loaded synchronously. Then, when this script runs it adds an event listener for `DOMContentLoaded` instead of `WebComponentsReady`, which subsequently fires _before_ all the imports (including `d2l-intl`) have loaded.
> not resolving WebComponentsReady promise until imports have loaded

- sass/navigation/logo.scss
Remove `display: table`, as the logo no longer has `display: table-cell`.
> DE32168 - Cert Fix - 10.8.9 - Fix logo centering in Firefox

- sass/navigation/logo.scss
Applying the fix from https://github.com/Brightspace/brightspace-integration/pull/1139 to `master` (10.8.10) as well.
> DE32352 - Fix logo centering in Firefox

- js/d2l-web-components-ready.js
- js/index.js
- test/web-components-ready.js
- web-components/bsi.html
This fixes `DE32339`, which was a bug with the navbar's chomper where it initially thought it had more room than it ended up with, causing the "more" menu to contain too few links.
There'll be a corresponding code change to the monolith to have it set `d2lWCRDispatched` and call `D2L.WCRDispatched()`. This change will be replicated in the `polymer-2` and `polymer-3` branches.
What was happening: in non-Chrome, about 10% of the time when this code ran, `WebComponents.ready` was `true`, causing it to add an event listener for `DOMContentLoaded` instead of `WebComponentsReady`. This means the polyfill had loaded, but for whatever reason the event hadn't been fully dispatched yet and web components hadn't upgraded.
For the navbar, this meant that its CSS hadn't yet been applied when the …
> adjusting the WebComponentsReady promise to always wait for the event

- package-lock.json
Checked on my local instance, I'm no longer seeing the "already registered" error
> Update package-lock to get latest version of activities branch

- sass/navigation/common.scss
- sass/navigation/course-menu.scss
- sass/navigation/divider.scss
- sass/navigation/header.scss
- sass/navigation/logo.scss
- sass/navigation/mobile-menu.scss
- sass/navigation/notifications.scss
- sass/navigation/personal-menu.scss
Two fixes here:
1. Applying the branding colours to non-links like the course name, which end up just being inside a `<span>` and not an `<a>`
2. While verifying the fix I noticed that all the CSS in `navigation/common.scss` was getting included **8 TIMES**, since it was imported into 8 different SCSS files. It only needs to be imported once, haha. This saves ~44KB in download size, yikes!
> Fix navbar non-links

- package-lock.json
- sass/navigation/common.scss
- sass/navigation/logo.scss
- sass/navigation/mobile-menu.scss
This pulls in the fix to the navbar logo from `master` to `polymer-3`.
@dbatiste FYI this is reverting your `package-lock` changes, similar to what @awikkerink had. I'm using NPM `6.7.0` so this must be a change in newer versions... you may want to update. I also wonder if this will solve some of the issues we've been having!
> Refresh polymer-3 from master

- sass/button.scss
This reverts most of #1193 and keeps only the part that re-applies `width: auto` on buttons. In Edge, because the polyfill reuses our `d2l-button` CSS class for the `<d2l-button>` web component's `button` element, it gets `width: 100%` on all buttons.
There will be a corresponding change in LP that will ensure button styles are inlined and do not use generated classes anymore. Otherwise this `width: auto` would always be more specific than those generated styles.
> only re-applying width to override Edge

- sass/navigation/common.scss
- sass/navigation/main-image-based.scss
- sass/navigation/main.scss
- sass/navigation/mobile-menu.scss
The code that put this CSS class on things [was removed](http://search.dev.d2l/source/diff/Lms/platformTools/navbars/D2L.PlatformTools.Navbars/Web/Desktop/Rendering/Views/Daylight/NavigationView.Renderer.cs?r2=%2FLms%2FplatformTools%2Fnavbars%2FD2L.PlatformTools.Navbars%2FWeb%2FDesktop%2FRendering%2FViews%2FDaylight%2FNavigationView.Renderer.cs%4084d0612c&r1=%2FLms%2FplatformTools%2Fnavbars%2FD2L.PlatformTools.Navbars%2FWeb%2FDesktop%2FRendering%2FViews%2FDaylight%2FNavigationView.Renderer.cs%4002c9f016), so there's no need for any CSS to target it.
I'll do a separate PR that also removes `d2l-navigation-s-has-branding` since it's now always present and so also doesn't need to be called out.
> removing "d2l-navigation-s-no-branding"

- sass/button.scss
Further change from the previous one as button margins were also impacted by the Edge issue.
> adjusting CSS for button margins so they work in Edge

- sass/navigation/common.scss
- sass/navigation/mobile-menu.scss
Removed the code where `d2l-navigation-s-course-info` is applied, so the css is no longer used.
> US102738-remove the no longer used css

- test-package-lock.js
This improves the logic in the checking we do that ensures our web component dependencies don't end up getting nested in the `package-lock.json`. If they do, that results in multiple versions of the same web component getting included in the bundle.
Previously, this was just looking for all `d2l-*` components. That misses out on non-D2L web components like `s-html` or `iron-icon`. Instead, I'm checking to see if a dependency requires Polymer, which likely means it's a web component. Additionally I added `d2l-hypermedia-constants` since it doesn't actually include Polymer.
> Checking for all Polymer dependencies

- web-components/d2l-activity-alignments.js
I'm pretty sure this is all that's required to get `d2l-activity-alignment-tags` rendering in the LMS, but please correct me if I'm wrong.
> Pulling in d2l-activity-alignment-tags from d2l-activity-alignments

- .travis.yml
Ran into this while working on the BSI improvements.
Basically while any step in the `script` block failing will fail the build, it doesn't prevent the subsequent steps from running. That's kind of what we want for the `test` and `build` bits... they can both run and fail, but we certainly don't want the deploy step to run if either of the previous two failed.
Another option is to move the publish into an `after_success` section, however then if it fails it doesn't fail the build... which we want.
> only publishing if previous build steps have passed

- .travis.yml
There's been a quiet error message in recent travis builds for BSI: `/home/travis/.travis/functions: line 104: [: missing `]'`. It doesn't seem to cause a failure, but it's the only thing that stands out to me as why my tagged build didn't publish to cdn.
I'm hoping this fixes it.
> Add a space to the new conditional

- cli/autotag.js
It turns out `ReleaseStartDate` is the Last Call Date, so starting just now `20.19.6` is in range of our query, which is resulting in 2 releases coming back.
Temporary fix is to take the first one (which is `20.19.5`) just to get this working quickly for folks. I'm going to try and either sort them (so the first one is guaranteed to be the one we want) or look into querying milestones instead of releases.
> [skip publish] temporarily fix

- cli/autotag.js
Here's a more permanent fix for this. It orders the releases by dev-done date and picks the earliest one.
> [skip release] ordering the releases before taking the closest one

- sass/navigation/personal-menu.scss
* Should be 6px border radius to match spec for medium profile image http://design.d2l/components/profile-images/
* I think it was maybe missed at some point, the anonymous profile image seems to already be using 6px as well
* I have checked in with design
Adjustments for the part circled in red
> US105083 - Updating radius border from profile image icon in nav-bar

- cli/autotag.js
- package-lock.json
- package.json
This ended up being a super weird Rally bug. When we query Rally to find active releases using the current date, those queries don't seem to support passing in hours. So we can't rely on the query to filter the active release down for us.
I changed it so that the hours are zeroed out before the query, but then we'll get back the current and next release more often. I then use the current EST time to determine if the first release that comes back is still active and if it's past noon yet on release day.
I threw in `console.group()` to clean up the console logging a bit as I used it a lot to test this out.
> Fix Rally query

- .travis.yml
Seems like Travis just turned their stable `node` version to version 12, which is causing lots of trouble.  Locking at version 11 for now to unblock other work, and we can investigate the issues with `node 12` (and the dreaded `npm 6.9.0`) tomorrow.
> Lock node version to 11

- package-lock.json
Update commit hash: https://github.com/BrightspaceHypermediaComponents/activities/commit/83fb487ed003923082ffba93826bc5d78d17f999
https://github.com/BrightspaceHypermediaComponents/activities/pull/177
> Apply cert fix US106128 to 20.19.5

- package-lock.json
I think this will solve the problem where npm i didn't seem to get the right version, causing polymer serve to fail on the release branch. After diffing what was in node_module/d2l-sequences and the sequences repo in the release/20.19.5 branch everything seemed to match
> Fix Sequences

- cli/autotag.js
I can't really explain how this was working before... but I swear it was! All of a sudden, the normal JS Date methods are no longer there... maybe they never were. This switches to use the moment methods to get the year, month and day.
> fixing to use propert moment API

- package-lock.json
- Fix Edge and IE11 if detached called twice
- Change to use `d2l-button-icon` (tested the monolith use with Manage Exemptions, looks good)
> Bump simple-overlay version

- sass/navigation/main-image-based.scss
Update the image based nav links hover and focus for wcag 2.1.  Group icon placeholder border darkened slightly so it still stands out against new hover background.
focused, normal, hovered
focused & hovered
tray opener focused
> Updates to image-based nav for wcag 2.1

- package-lock.json
Bump activities to 3.2.3:
https://github.com/BrightspaceHypermediaComponents/activities/releases/tag/v3.2.3
> Bump activities

- README.md
I was churning a good amount yesterday trying to figure out why npm i wasn't flattening properly, and found that i needed to go a bit nuclear.
Would this blurb in the readme be useful for anyone else? or is it fairly common knowledge?
> add a blurb for resolving weirdness in package-lock.json

- package-lock.json
1. US107704: Add the context menu to the d2l-enrollment-hero-banner
1. DE34864: Fix the summary view meter bar to correctly fill in IE11
1. DE34865: While in IE11, the Checkmark and Continue indicators are showing right next to Module titles.
> Bump version for d2l-sequences and d2l-enrollments

- package.json
- web-components/bsi.js
This seems safe, but could use a second opinion.
`iron-iconset-svg` is no longer used in BSI (@dbatiste cleaned that up recently) and isn't used in the monolith. Ditto for `iron-icon`. This change resulted in no change to the `package-lock` file, which isn't surprising since other things inside BSI are still using them.
The only "risk" I can think of is that when `d2l-icons` stops pulling these in, then in theory if another dependency in BSI was using one of them but not importing it, it would break.
> removing unused dependencies on iron-icon and iron-iconset-svg

- web-components/bsi.js
This turns off Polymer's ghost click handling, used for old mobile browsers.  This is causing issues selecting radio buttons in iOS with VoiceOver, because of the use of double-tap to select an option.
Based on my testing, turning this off doesn't seem to have any negative affects.  The PR that adds this fix (https://github.com/Polymer/polymer/pull/5533) for the Polymer issue (https://github.com/Polymer/polymer/issues/5289) mentions that this is not needed anymore and links to this article: https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away.  We are already adding `<meta name="viewport" content="width=device-width">` to the `head` like it suggests.
Aside from radio buttons, disabling this also fixes some other issues being caught by the same thing - for example, …
> DE35087 - Disable Polymer's Synthetic Click Canceling

- sass/navigation/personal-menu.scss
When we go to Lit, `<d2l-icon>` no longer supports the `src` attribute. This is used [in the LMS](https://github.com/Brightspace/lms/blob/35710600e328bbbe45a792d8ffc3371957d05a0f/platformTools/navbars/D2L.PlatformTools.Navbars/Web/Desktop/Rendering/Views/Daylight/PersonalMenuHandle.Renderer.cs#L94) in the old personal menu rendering code. This will be switching to just use an `img` tag instead, but that will need this CSS applied to it as well.
> personal menu can soon be both d2l-icon and img

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/activities/releases/tag/v3.24.0
@dlockhart I can hold off on merging this until you give the go ahead - don't want to mess up your test
> Bump activities to 3.24.0

- package-lock.json
Bump `d2l-polymer-siren-behaviors` to get the fix for the duplicate course cards in my-courses
No other changes had been made since: https://github.com/Brightspace/polymer-siren-behaviors/compare/6555ed4f59e6fb60adeaf9b988acdf2314f077d6..3899289c473bde7fb52de585cc10e88012b20a89
> DE35555 - Add fix for duplicate my-courses cards into 20.19.8

- README.md
Pulling in these instructions, which [previously lived in The Guide](https://github.com/BrightspaceUI/guide/wiki/Wiring-up-to-locally-run-a-web-component-&-BSI-on-your-dev-LMS).
I think this is a more appropriate place for them -- right next to BSI itself -- and will result in a higher likelihood of them being kept up to date.
> adding instructions for local component development

- web-components/bsi.js
Since there is a story to add this to BSI. My understanding is you want to write this component into the middle slot. Somewhere around https://search.d2l.dev/xref/lms/lp/framework/web/D2L.LP.Web.UI/Desktop/Controls/ImmersiveNav/ImmersiveNav.Renderer.cs?r=31480c86#66
Does that sound right?
> US109398 - Allow subtitle component to be used in BSI

- package-lock.json
This contains:
* https://github.com/BrightspaceHypermediaComponents/activities/pull/314
* https://github.com/BrightspaceHypermediaComponents/activities/pull/315
> Backport activities changes to 20.19.9

- package-lock.json
Fills in stubbed out Lores API call for a real one now that Lores is updated
> Update Program Outcomes Picker to 3.0.3

- package-lock.json
- polymer.json
An unforeseen result of the work done in https://github.com/BrightspaceHypermediaComponents/activities/pull/415, since `d2l-activities` is using `fetch` rather than `import` to fetch its translations, the BSI build ends up excluding the files from the build. Sadly, adding them to the `extraDependencies` in that repo isn't sufficient, and they still get skipped, whereas adding them here does work.
This is probably another small factor that leans us towards a better solution, possibly a build script - having to explicitly include each repo's JSON language files here would be pretty messy. This PR does get things back to working, though.
> Add d2l-activities Serge JSON files dependencies

- cli/define-replacer.js
- package-lock.json
The latest version of babel is wrapping `define` even if we already wrap it: https://github.com/babel/babel/issues/10512.  This is now included in our `shared_bundle_1.js` file:
```
"function" == typeof define ? define(function () {
return exports
}) : "object" == typeof module && (module.exports = exports)
```
This PR updates the regex of the replacer to catch and replace " define?define(" with " define2?define2(".
(I'm also updating the version of babel below, but that doesn't fix things.)
> Fix BSI define error

- package-lock.json
No changes have been made to `d2l-organizations` since the last update in 20.19.22, and the only changes to `d2l-image-banner-overlay` between the last version and this version were around the `package.json` file: https://github.com/Brightspace/d2l-image-banner-overlay/compare/1830e009cad4e0d3b23916b6da3953203a90b4d7..9d32a32c5e8d258bdb836e7d233de318cd46e251
> DE36611 - Bump organizations and get langterms for image banner for 20.19.11

- polymer.json
I am having the same problem that was described in this commit
https://github.com/Brightspace/brightspace-integration/commit/29df38ca5d6d5d785a1095381d7c064fa3cca866#diff-2d9e645fa178242a8fe6ccfbeafe0d20R29
because the localization file I am using in d2l-organization-availability-set is the same as the one from d2l-activity-editor in d2l-activities so I have the same issue.
> Include d2l-organization-availability-set lang files in build

- sass/inputs.scss
Some UMD FRAs (like Awards) were depending on the `vui-input` CSS class to be present on the page in order to style `<select>`s and other things.
Correctly or incorrectly (I'd argue incorrectly as this was never how UMD FRAs were supposed to work), they're broken now. This is a relatively easy and painless fix to un-break them while still allowing us to remove the `vui-input` class from the MVC/legacy code and move forward.
I'm still going to make some improvements to Awards as I'm already in there.
> bringing back the "vui-input" class for UMD FRAs

- sass/html-editor/group.scss
- sass/html-editor/html-editor.scss
- sass/html-editor/shared.scss
Corresponding change coming in the LMS.
These changes support the concept of "bordered" HTML editor toolbar groups (all the existing ones) and non-bordered (`<select>`-based ones).
It also stops overriding the borders of `<select>`s (except toning down the colour to match the other items).
> updates to support new select styles in the HTML editor

- package-lock.json
Siren SDK was already bumped in PR#1739. This updates d2l-activities to bring in the rest of the front end changes for US111803: https://rally1.rallydev.com/#/110294864140d/detail/userstory/349211942424
> Bump d2l-activities

- package-lock.json
This PR bumps d2l-activities (fyi @AllanKerr, @kieranderson) and siren-sdk (fyi @kieranderson) to get the date stuff and the turnitin stuff.
> Bump d2l-activities, siren-sdk

- .npmrc
- package.json
Node 6.8.0 is the  "preferred" version for BSI as higher versions can cause a variety of issues. Seems like this should be a hard limit to prevent people from experiencing unnecessary pain.
(Can surely squash if that causes some pain for you that I don't see, but seems to be a common question)
> Don't allow incompatible npm versions

- sass/dialog.scss
These updates are needed so that these styles do not target internal elements of d2l-dialog web components when shadow-DOM is not supported (Edge). 
The classes that are in conflict are:
* d2l-dialog
* d2l-dialog-inner
* d2l-dialog-footer
A couple updates for the d2l-dialog-inline were needed to maintain specificity for proper dimensions of MVC inline dialogs.
> Updates to dialog CSS selectors.

- polymer.json
Forgot that we need to include the langterm files explicitly here. Strangely, Chrome seems to still half-work without these, but Edge blows up entirely and doesn't work with attachments.
> Fix FACE attachments

- polymer.json
Similar to #1770, but for icons this time! Need to explicitly include these are they are not `import`ed anywhere in Brightspace/attachments, but rather referenced using `resolveUrl`.
> Explicitly include attachment icons

- package-lock.json
Bump activities to backport (or is it hotfix now) the refresh bugfix and langterms
https://github.com/BrightspaceHypermediaComponents/activities/compare/14837b219d751b430864f0c5f581f1aa403eafac...c3646f03c7c5fc43edb6b5293d37cf8e1e5783f0?w=1
> Backport refresh and langterms

- unbundle-script/unbundle.py
This is addressing the bug that if you run `python3 unbundle.py --component-path="<path>" -d` you should not receive any errors and not require any further flags.
> Run BSI unbundle script with dry flag without getting any errors

- package-lock.json
This picks up the version of core that doesn't have our Intl stuff in `LocalizeMixin`, as well as the version of activities that no longer uses them.
> upgrading to core 1.28

- es-dev-server.config.js
- package.json
Copied from es-dev-server README but replaced deprecated jsnext/browser fields with mainFields.
https://github.com/open-wc/open-wc/tree/master/packages/es-dev-server#node-resolve
> add node resolve config to favour es modules to fix commonjs import issues

- web-components/bsi.js
Include the `d2l-backdrop` component - to be used by ifrau (host) to place backdrop behind iframe when dialogs are open inside the iframe, although other things may use it in the future too.
> Include the d2l-backdrop component.

- package-lock.json
bumping to > https://github.com/Brightspace/d2l-sequence-viewer/releases/tag/v1.5.5
> bump sequence viewer version

- package-lock.json
Backporting to 20.20.2 
DE37638: (20.20.2) Cannot advance through activities/Survey on iPhone and Pulse App (Version 13.1.3)
Viewer version: https://github.com/Brightspace/d2l-sequence-viewer/releases/tag/v1.5.7
> DE37638 - bump sequence viewer

- package-lock.json
This pull request includes cert fixes for the following repos:
- `d2l-activities`: https://github.com/BrightspaceHypermediaComponents/activities/tree/release/20.20.2
- `d2l-enrollments`: https://github.com/BrightspaceHypermediaComponents/enrollments/releases/tag/v4.0.34-cert
- `d2l-organizations`: https://github.com/BrightspaceHypermediaComponents/organizations/releases/tag/v5.1.59
> Learning Paths Cert Fixes

- package-lock.json
[DE34471](https://rally1.rallydev.com/#/detail/defect/309752498680?fdp=true): Out of order points error message does not go away if you correct the point order by editing a cell that does not have the error associated with it
> Bump d2l-rubric

- package-lock.json
Bumping to hotfix version for 20.20.1 https://github.com/Brightspace/d2l-sequence-viewer/releases/tag/v20.20.1-hotfix
> Update sequence viewer version for DE37477

- package-lock.json
Bump:
To: https://github.com/BrightspaceHypermediaComponents/enrollments/releases/tag/v4.0.34-cert5
From: https://github.com/BrightspaceHypermediaComponents/enrollments/releases/tag/v4.0.34-cert4
> Bump enrollments to include the My Courses lang term fix

- package-lock.json
I only bumped enrollments because of how close we are to branching since we may have to backport this version to 20.20.3 cert. These commit hashes for enrollments are sequential so the lang term fix is the only change.
> Bump enrollments for MyCourses lang term fix

- package-lock.json
- package.json
- rollup/rollup.config.js
Switches to use rollup for the uglify step of the `bsi.js` non-web-component JavaScript bundle.
I diff'ed these and the output is identical.
One change: I removed the generation of the source map file, since we don't actually publish any of the original source files to the CDN so the source map doesn't actually work anyway.
> moving uglifyjs build step into rollup

- package-lock.json
Updating sequences to https://github.com/BrightspaceHypermediaComponents/sequences/releases/tag/v1.5.5 to bring in the 20.20.3 translations
> DE38061 - bumping sequences for cert

- sass/deprecated/icons.scss
- sass/vui.scss
This css has been moved directly into the monolith.  This won't be merged until after https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/8947/overview is merged.
> Remove sass file importing from the old icons repo

- package-lock.json
20.20.3 translations
Rubrics: https://github.com/Brightspace/d2l-rubric/releases/tag/v3.7.4
Outcomes-user-progress: https://github.com/Brightspace/d2l-outcomes-user-progress/releases/tag/v1.4.2
> Bump rubrics and outcomes user progress for translations

- sass/dialog.scss
This fixes a regression on the selectivity of MVC inline dialogs on mobile - specifically, the width of the inline dialog should be `100%`, not `60vw`.
> DE37820 - Fix selectivity of mobile inline dialog CSS

- package-lock.json
[US111975](https://rally1.rallydev.com/#/detail/userstory/351535324260?fdp=true): [SSR][Authors] Send alerts
This PR updates insights-portal.svg to fix cut-off version of icon
PR that added the icon https://github.com/BrightspaceUI/core/pull/421
`package-lock.json` diff is tiny for my change.
> US111975 [SSR][Authors] Send alerts. Use new insights-portal icon

- package-lock.json
This PR bumps frau-publisher so that the language XML files are served with compression from the CDN.
> Bump frau publisher

- package.json
- rollup/rollup.config.js
DO NOT MERGE until [monolith PR merges](https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/11005/overview).
Once renegerator-runtime is referenced from the CDN, we no longer need to publish it with each BSI bundle.
> removing regenerator-runtime from BSI bundles

- package.json
I'd like to use `npm start` as the script name for the new Rollup-based developer builds when they're ready. To make it easier to integrate both build systems together in parallel (for a little while until the old one goes away), I'd like to rename this one to `start:legacy` and alias it.
> aliasing legacy start script

- serve.bat
I reached out on #web-platform to see if anyone's relying on this and so far no one. I'd like for it to be gone as the concept of "serve" is going to change with the unbundled builds.
> removing serve.bat batch file as it's redundant with "npm run serve"

- .browserslistrc-es-dev-server-legacy
- .browserslistrc-open-wc
- package.json
Renaming the `es-dev-server` one as I want to use it for the new open-wc Rollup builds as well.
Also simplified it a bit so that it can be identical to the `.browserlistrc` except with the additional `not IE 11` (open-wc handles IE11 for us).
> aligning browserlistrc files

- cli/autotag.js
Was seeing this warning in the build output:
> [@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
> fixing warning for deprecated oktokit import method

- package-lock.json
The `my-courses` version was actually updated in https://github.com/Brightspace/brightspace-integration/pull/2073, but want to get my `siren-sdk` deletion as well.
> Update siren-sdk version

- package-lock.json
Updating to use this release of activities https://github.com/BrightspaceHypermediaComponents/activities/releases/tag/v3.52.176 and this release of rubrics https://github.com/Brightspace/d2l-rubric/releases/tag/v3.7.19
> Updated activities to v3.52.176 and rubrics to v3.7.19

- package.json
- web-components/bsi.js
Shouldn't actually change anything, including `package-lock` since other projects are still referencing it.
> referencing alerts directly from core

- rollup/rollup-wc.config.js
- web-components/bsi-unbundled.js
- web-components/bsi.js
This is in preparation for using unbundled alerts and toasts. Unfortunately the toast import can't actually be unbundled for the reasons listed.
> adding unbundled alert assets

- package-lock.json
This changes sequences to use [v1.15.16](https://github.com/BrightspaceHypermediaComponents/sequences/releases/tag/v1.5.16) and sequence viewer to use [v1.7.2 ](https://github.com/Brightspace/d2l-sequence-viewer/releases/tag/v1.7.2)
> DE39183: update sequences and sequence viewer

- package-lock.json
- package.json
https://github.com/Brightspace/d2l-my-courses-ui/releases/tag/v11.5.2-hot-fix-1
> [20.20.5] - DE39205 - Bump my-courses version

- package-lock.json
- package.json
This is the cert fix version of the fix to the all courses overlay issues in legacy edge.
> [20.20.6] - DE39211 - Bump my-courses and core

- rollup/rollup-wc.config.js
In the legacy Polymer builds, there are a bunch of [extra dependencies](https://github.com/Brightspace/brightspace-integration/blob/master/polymer.json#L34) that it doesn't notice, so need to be called out specially and copied.
The same is true with the unbundled builds, so we need to handle them specially. I'm not sure what the ideal solution is here... but for at least language files it would be ideal if they were dynamically imported.
> supporting statics from polymer.json in unbundled builds

- unbundle-script/unbundle-tests.py
- unbundle-script/unbundle.py
@DiljotSG would you be able to test this out for me? I run BSI from my Mac so the script itself doesn't work for me.
Essentially when the new unbundled builds are ready, `"env": "dev"` needs to get added to the monolith config file, which will do the same thing as `"import-style": "esm"` did. So this sets them both for now, and then when unbundled builds are always-on I'll remove the import-style stuff.
> updating script to also apply "dev" environment

- .travis.yml
- package.json
@kieranderson we chatted about this a couple weeks ago on Slack.
This breaks out the Oslo lang build step so that it only runs in CI, instead of each time a developer does a local build.
> separating out the oslo lang build

- es-dev-server-dev.config.js
Watch is meant for apps, and we're not using open-wc in that way.
> no need to watch in dev mode

- .dependabot/config.yml
It doesn't play well with the repos that are included as github urls.
They get bumped as casualties on random package bumps which isn't workable.
From @dlockhart : the PRs it generates have diffs like
```diff
-        "d2l-polymer-behaviors": "github:Brightspace/d2l-polymer-behaviors-ui#semver:^2",
-        "d2l-resize-aware": "github:BrightspaceUI/resize-aware#semver:^1",
+        "d2l-polymer-behaviors": "github:Brightspace/d2l-polymer-behaviors-ui#a5dfce6568e1e13ac58895ef3bb47131f1342cd1",
+        "d2l-resize-aware": "github:BrightspaceUI/resize-aware#96ba3ac560380abfb753f128ac9a5c0992d7d723",
```
which won't work.
I'll turn on security alerts (not PRs) independently.
> Disable dependabot for now

- package-lock.json
- package.json
This will prevent a recurrence of the mobx issues we were seeing this morning. Once consistent-eval is using `0.0.3` of mobx like the others, this can be unlocked again.
> locking consistent-eval at 0.0.22 until they sort out their mobx issues

- package-lock.json
- package.json
Leveraging @AntonBazhal's change to just use the peer dependency on `eslint`.
> upgrading eslint-config-brightspace which uses the peer dependency

- rollup/rollup-wc.config.js
- web-components/bsi-unbundled.js
- web-components/bsi.js
This will have a corresponding change in the LMS, but will have to merge ahead of it to ensure that this asset is on the CDN for the LMS's asset verification tests to pass. In the interim, bundled builds will be fine but unbundled builds will just be missing the save-status indicator in quizzing -- which is OK for now since the feature flag is off.
> unbundling save-status

- rollup/rollup-wc.config.js
- web-components/bsi-unbundled.js
- web-components/bsi.js
Saves about `7 kB` from being downloaded, parsed and executed on every page. :)
Will require a change in the LMS but this needs to merge first. In the meantime, only the unbundled builds will be missing the consortium tabs.
> unbundled consortium tabs

- rollup/rollup-wc.config.js
- web-components/bsi-unbundled.js
- web-components/bsi.js
Saves about `9 kB` from being downloaded, parsed & executed on every page. Only used once in the LMS -- PR there coming shortly but this will need to merge first.
> unbundled switch

- package.json
- web-components/bsi-unbundled.js
This is a temporary measure until I can figure out a longer term solution to Capture using these custom elements -- either loading these modules from Capture, switching Capture to use something else, or wrapping them in MVC controls (which may not make sense).
Usages in Capture:
https://search.d2l.dev/xref/lms/mp/D2L.WCS.MP.Web/Controls/VideoCapture/VideoCapture.cs?r=8c179a86
> explicitly including some components required by Capture

- package-lock.json
- Backport of this fix: https://github.com/BrightspaceUI/core/pull/640
> Backport core 1.51.2 to 20.20.7

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/activities/commits/release/20.20.7
https://rally1.rallydev.com/#/29180338367d/detail/defect/397885411452
> DE39499 Cert 20.20.7: Update d2l-activities for translation updates

- package-lock.json
Backporting LX DocReader support
Bringing in this sequence-viewer release https://github.com/Brightspace/d2l-sequence-viewer/releases/tag/v1.7.2-hotfix
> DE39605: update sequence viewer version

- js/bsi.js
- js/d2l-web-components-ready.js
- test/web-components-ready.js
Corresponding PR in Brightspace:
https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/13415/overview
This change will delay the page "fade-in" until after our web fonts have loaded in browsers that support the FontFace API. It does so in a similar mechanism to how we wait for web components today. The hope is that this helps prevent a "flash of unstyled text" from occurring in some instances.
If things take too long (>2s), we assume something has gone wrong loading the fonts and we just fade-in regardless.
> waiting for web fonts to be loaded before fading page in

- rollup/rollup-wc.config.js
- web-components/bsi-unbundled.js
- web-components/bsi.js
Will require the loading of this from the AppLoader, which will happen in a new iFRA plugin for the WC dialog.
> unbundling the backdrop component

- sass/navigation/common.scss
[**DE39554**](https://rally1.rallydev.com/#/15545167705d/detail/defect/398847069340?fdp=true)
The following changes were made in this PR:
~ Replace text-decoration with a bottom border for navigation links
NOTE: In the demos below, I used the keyboard to navigate through the links, then used the cursor to hover over the links.
**Before:**
**After:**
> DE39554 - [NYU Accessibility: 2.1] Navigation > Accessibility > Top-Level Navbar > Focus Indicator too Subtle

- package-lock.json
Siren-sdk: https://github.com/BrightspaceHypermediaComponents/siren-sdk/releases/tag/v1.10.73
Activities: https://github.com/BrightspaceHypermediaComponents/activities/releases/tag/v3.52.251
> Update activities and siren-sdk versions

- rollup/rollup-wc.config.js
- web-components/bsi-unbundled.js
- web-components/bsi.js
This saves about `1.5 kB` from each page. Corresponding PR in the monolith to dynamically load this in the few places that need it.
> unbundling the loading spinner

- README.md
- test-package-lock.js
This is draft for now as it's going to intentionally fail CI until `consistent-eval` is using the same version of mobx as everyone else. But had this check been in place, the issue never would have been introduced in the first place.
Update: everything is using the same mobx now, so should be good.
> including mobx in the list of front-end dependencies we check against

- .travis.yml
`npm run build` blows away the `build` directory, which would delete the Oslo files. 🤦
> building lang last

- package-lock.json
- Pulls in a patch release version of `brightspace-ui/core` v1.59.5
- [DE39813](https://rally1.rallydev.com/#/detail/defect/405152852372?fdp=true): Dragging and dropping a list item in a Learning Path intermittently redirects to a Google search for "undefined" on iPad Safari
- Show drag handle on touch devices
- Adds drag n drop support for touch devices
- Lint fixes
> Added patched version of core

- web-components/bsi-unbundled.js
I removed the one place in the monolith that was using a `<d2l-link>` web component yesterday as [part of this PR](https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/14059/overview). That means we no longer need to include it on every page! 🎉
> removing d2l-link

- rollup/rollup-wc.config.js
Not ready to remove this from `bsi-unbundled.js` yet as lots of stuff in the monolith is still using subtle-buttons without loading the module, but this is a first step.
> unbundling subtle button

- sass/navigation/common.scss
- sass/navigation/main.scss
This defect required a certfix because of two things:
~ the colour for the underline on navigation links was always `d2l-color-celestine` regardless of the colour of the link text itself
~ the navigation links that were dropdowns were still using the old styling (i.e. using text-decoration instead of the thicker border-bottom)
The following changes were made in this PR:
~ removed colour from border-bottom property for navigation links (colour will be inherited now)
~ replaced text-decoration with a thicker border-bottom for navigation links that are dropdowns
***
**Before:**
NOTE: Used Spark to show the issue with underline colour.
***
**After:**
NOTE: Applied the same colour (using navbar themes) on my local instance to test the underline colour.
> DE39554 (Certfix) - [NYU Accessibility: 2.1] Navigation > Accessibility > Top-Level Navbar > Focus Indicator too Subtle

- oslo/LangPackage.js
Added attribute for setting langtype for webcomponent lang xml, we can parse this in the LAIM tool to determine what to set the term type to.
The new XML:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<package name="WebComponents" type="Language" langtype="ICU" toolid="0" version="0.0.0.0">
<collection name="d2l-activities\activityCard" type="Standard">
<langTerm sortOrder="1" name="course">
<defaultValue><![CDATA[Course]]></defaultValue>
<description><![CDATA[]]></description>
</langTerm>
...
```
> US114907 Set WebComponent lang type to ICU in the XML file

- package-lock.json
- package.json
* This will get Maya's fix to the width of leaderboard --Keeps correct core version
--Changes needed after updates to list component
> (20.20.8) Set Awards leaderboard to version 1.0.14

- sass/homepages/homepages.scss
This feature flag has been removed and the CSS class is [always applied](https://search.d2l.dev/xref/lms/platformTools/homepage/definition/Web/Desktop/MasterPages/Default/HomepagePageFactory.cs?r=f326ca6a#76), so to simplify I'd like to just remove it.
> removing the widget demarcation class

- package.json
- web-components/bsi-unbundled.js
This saves 2 requests and 2138 bytes from every page.
> removing polymer behaviours expand-collapse

- web-components/bsi-unbundled.js
Nothing is left that's directly creating subtle buttons or button-icons without going through the MVC controls that do the import. 🎉
> unbundling button-icon and button-subtle

- package-lock.json
[DE39269](https://rally1.rallydev.com/#/110294864140d/custom/110851118712?detail=%2Fdefect%2F394449702920&fdp=true)
Hide the rubrics label if the user doesn't have permissions
[DE39958](https://rally1.rallydev.com/#/110294864140d/custom/110851118712?detail=%2Fdefect%2F408302156092&fdp=true)
Hide the RC Header if the user doesn't have manage delivery permission
> Activities bump to release v3.53.1

- package-lock.json
bumped version of `@brightspace-ui/core`
> bumped version of brightspace-ui/core to 1.72.7

- web-components/bsi-unbundled.js
The LMS is using the `d2l-status-indicator` but we don't explicitly include it.  My guess was that it used to be included "for free" with something else in the bundle, and that got moved out.  We'll want to unbundle this and have the LMS load the module, but just trying to fix the problem for now - there's probably some cleanup that can happen in the LMS to get the legacy component using the MVC one.
> Fix missing d2l-status-indicator in the LMS

- web-components/bsi-unbundled.js
Cert version of https://github.com/Brightspace/brightspace-integration/pull/2423
> 20.20.9 - Fix missing d2l-status-indicator in the LMS

- package-lock.json
[US119539](https://rally1.rallydev.com/#/110294864140d/custom/110851118712?detail=%2Fuserstory%2F414155548564&fdp=true)
version bump to get [this](https://github.com/BrightspaceUI/core/pull/818) change to check the blobs dictionary for a request/response
> version bump core

- package-lock.json
- package.json
- web-components/bsi-unbundled.js
- This allows early load scripts to wait until the logging library has loaded and
create their own logging clients without having to import it explicitly.
> Add Logging Integration

- package-lock.json
This is a fix for DE40387. 
We have a new version of leaderboard that drops the unneeded leftover FRA auth bits
> Update leaderboard version

- .serge-mapping.json
[DE40300](https://rally1.rallydev.com/#/110294864140d/custom/110851118712?detail=%2Fdefect%2F421999746960)
[PR](https://github.com/Brightspace/lms/pull/1009) where the terms for these collections are deleted in the database
[PR](https://github.com/Brightspace/lms/pull/990) to delete old activity lang terms from the database
> delete collections that are not activity from serge-mapping

- package-lock.json
- web-components/bsi-unbundled.js
- Instead the `d2l-logging-loaded` event now includes `createClient` in its detail
> Remove the D2L.Logging global

- package-lock.json
DE40524 FACE activities Assignment type not properly disabled
DE40501 due date always empty on first load
> [20.20.10] Bump activities to include CERT fixes - DE40524, DE40501

- package-lock.json
Updating BSI with latest version of sequences. Update includes a fix to prevent a JS error when viewing HTML topics in LX.
> bump sequences version to prevent JS error

- package-lock.json
Updating the rubrics commit hash for the package lock again, now with a github version bumped so we won't have to roll back.
* [New version created here](https://github.com/Brightspace/d2l-rubric/releases/tag/v3.7.32)
* [Original pr found here](https://github.com/Brightspace/brightspace-integration/pull/2457)
* [Revert due to github version missing here](https://github.com/Brightspace/brightspace-integration/pull/2476#discussion_r488695927)
> DE40414 Updating rubrics commit hash again

- .github/workflows/bsi-update.yml
It seems to think there is a diff every time even when nothing has changed since the last run on that branch, so I want to see what it sees.  I think this will be helpful for any future debugging, so probably going to keep it this way!
> Remove -s from the git diff command

- oslo/README.md
Updating the docs to use markdown and to mention the issue with the special characters. I want to link to them from the OSLO controller so people have more context on why we are going to parse `@` when retrieving from the DB in the code I added (in a different PR in the lms).
To view the markdown: https://github.com/Brightspace/brightspace-integration/blob/ushamim/usa/update-oslo-readme/oslo/README.md
> Update oslo readme

- oslo/Serge.js
- oslo/Util.js
This implements [US121057](https://rally1.rallydev.com/#/388869855380d/dashboard?detail=%2Fuserstory%2F439112983600&fdp=true) and causes the BSI build to fail if there are any characters in a term name that contain a forbidden character (for now that is only `.` but we may add more later).
> US121057 OSLO > Fail BSI build when there are invalid term names

- package-lock.json
- package.json
Bump `d2l-outcomes-level-of-achievement` to Major Version 3
BSI components that depend on this component:
* `d2l-consistent-evaluation`
* `d2l-activity-alignments`
> Bump `d2l-outcomes-level-of-achievement` to Major Version 3

- package-lock.json
- package.json
- rollup/rollup-wc.config.js
- web-components/d2l-discovery-app.js
Discover-FRA is being migrated into working as a BSI component. 
Therefore it'll need to be in BSI!
All old and unnecessary dependencies were removed from discover before this PR. The remaining paper dialog and dompurify will be much more easily removed post-migration.
> Add Discover as new BSI dependency

- web-components/bsi-unbundled.js
All references in the LMS are now going through the MVC control.
> unbundling dropdown-more component

- rollup/rollup-wc.config.js
We've avoided referencing this so far, but MVC `ButtonMenu` currently uses it in some pretty custom.
> exposing dropdown asset

- rollup/rollup-wc.config.js
- sass/navigation/main.scss
Noticed that only on legacy pages that navigation groups get an outline when focused:
MVC pages aren't impacted because the `reset.css` stylesheet removes all outlines. Not sure when this was introduced... it may have also been a recent Chrome change. 🤷
> Fix navigation group focus

- .github/workflows/bsi-update-merge.yml
- .github/workflows/bsi-update.yml
- cli/autotag.js
Adding the auto-merge action before the auto-approve to make it easier to test.  This is based on the one the LMS uses to auto-merge BSI PRs there.
> US121650 - Add auto merge GitHub action

- .github/workflows/bsi-update-merge.yml
The schedule did seem to fix it, I am getting the full list of PRs now and console logs about what it does with each one.  Removing for now to be sure and because I have to run and don't want it running every ten minutes without more testing.
> US121650 - Remove schedule for now

- package-lock.json
Picks up the changes to card that prevents a `null` `href` from being a link.
> upgrading to core version 1.85.3

- package-lock.json
In the 20.20.10 release, the commit hash of `d2l-outcomes-level-of-achievements` in `package-lock.json` points to a buggy version of Major Version 3, even though the major version of the component in `package.json` is 2.
Changes:
* Bump the commit hash of `d2l-outcomes-level-of-achievements` back to the latest commit hash in Major Version 2 (prior to LitElement conversion)
https://rally1.rallydev.com/#/detail/defect/445117376000?fdp=true
> Bump d2l-outcomes-level-of-achievements back to Major Version 2 (20.20.10)

- package-lock.json
- package.json
We want `master` of BSI to have the latest CE version as well
> manually bump consistent-eval to v1

- package-lock.json
- package.json
As the title suggests, the Discover dependency was updated to no longer use the temporary branch and instead use the latest release of it's bsi version (currently 3.0.2)
> Updated Discover version

- package-lock.json
Cert bumps for the following changes:
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/181
https://github.com/Brightspace/outcomes-level-of-achievement-ui/pull/64
https://github.com/Brightspace/d2l-outcomes-overall-achievement/pull/59
* Bump `d2l-consistent-evaluation` to v1.0.4
* Bump `d2l-outcomes-overall-achievement` to v1.1.30
* Bump `d2l-outcomes-level-of-achievement` to v3.0.13
> Bump repos for locked COA (20.20.12)

- package-lock.json
For DE41464 -  FACE Calendar gets cutoff while in mobile drawer
https://rally1.rallydev.com/#/detail/defect/458814880188?fdp=true
> Update Brightspace-ui/core version to 1.100.4

- package-lock.json
- package.json
Tested locally: checked Portuguese translations and verified new features (settings page) not included.
> engagement dashboard bump for 20.20.12 translations

- rollup/rollup-wc.config.js
TinyMCE only provides their free offerings in their NPM packages. Since the HTML editor component relies on plugins and skins from their Enterprise subscription offering (which we need to download directly), we need to manually add these to the editor repo. Unfortunately, because TinyMCE needs to use these files directly, we can't import them and need to add them to rollup as static files. ☹️
> Add static TinyMCE plugins/styles to BSI for the HTML editor component

- rollup/rollup-wc.config.js
- web-components/d2l-quick-eval-widget.js
This PR adds the `d2l-quick-eval-widget` application to BSI. It's already contained in `activities` so no need to change `package.json`
> Add d2l-quick-eval-widget

- package-lock.json
- package.json
Reason for hotfix:
Translations for "overall achievement" were not being applied - required for international accessibility. Fixed in latest release of d2l-outcomes-overall-achievement, and separately applied to a hotfix release.
Ticket: https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fdefect%2F462843020492
Related PR: Brightspace/d2l-outcomes-overall-achievement#69
Hotfix release: https://github.com/Brightspace/d2l-outcomes-overall-achievement/releases/tag/20.20.12-v1.1.33
> [HOTFIX] 20.20.12 - Bump d2l-outcomes-overall-achievement

- package-lock.json
This is for 2 cert defects
- [DE41695](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F463898537708&fdp=true?fdp=true)
- [DE41590](https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fdefect%2F461078835524&fdp=true?fdp=true)
> Update sequences version for 20.21.1

- package-lock.json
Cert fix for [bulk action](https://github.com/Brightspace/d2l-outcomes-overall-achievement/pull/71) and [improved error logging](https://github.com/Brightspace/d2l-outcomes-overall-achievement/pull/70)
> Bump d2l-outcomes-overall-achievement

- package-lock.json
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=/defect/484000074416
Bumping d2l-activities version for a hotfix related to assignment skeleton loading behaviour.
> Manually bump d2l-activities for hotfix

- package-lock.json
Pulling in the change described in https://github.com/BrightspaceHypermediaComponents/activities/pull/1388
> [Cert Fix 20.21.2] OSLO > Manual activities version bump to fix missing serge entry

- package-lock.json
Changes [can be found here](https://github.com/BrightspaceHypermediaComponents/activities/pull/1422).
> [Cert fix 20.21.2] activities version bump for weblink changes

- package-lock.json
- package.json
- rollup/rollup-wc.config.js
* updates dependency for d2l-opt-in-flyout since it was moved
* adds core d2l-input-textarea to roll-up config so it can be referenced in LMS
Note: a second PR will be made to remove `./node_modules/d2l-inputs/d2l-input-textarea.js` from the rollup config once it's reference in the LMS has been updated. (https://search.d2l.dev/xref/lms/mp/D2L.WCS.MP.Web/Assets/InputTextareaModule.codegen?r=3a00a5b5)
> Updates for d2l-input-textarea from core.

- .browserslistrc
We dropped support for the Extended Support Release of Firefox with the January release. Removing it from here will cause old-Firefox vendor prefixes from appearing in our CSS and stop Babel from doing special JS transpiling specifically for Firefox ESR.
> remove Firefox ESR from our browserlist

- package-lock.json
- package.json
- rollup/rollup-wc.config.js
- web-components/mathjax.js
This PR exposes the mathJax loader as a module that can be imported from the LMS (for Equation Editors), and also Content Topics. It is not included in `bsi-unbundled.js` because it will only be needed in those contexts, and it needs to be loadable on its own with out the other stuff that's in `bsi-unbundled.js`. The loader will have future changes to support configuration, but this one step towards hooking things up.
This PR is required for this LMS PR: https://github.com/Brightspace/lms/pull/5920
> Expose module for mathJax loader.

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/releases/tag/v1.39.3
> update CE to 1.39.3

- package-lock.json
Rest of languages coming later this week.
PR: https://github.com/Brightspace/d2l-outcomes-overall-achievement/pull/106
Release: https://github.com/Brightspace/d2l-outcomes-overall-achievement/releases/tag/v1.1.42-20.21.2-hotfix-1
Rally: https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fdefect%2F490046520960
> DE42328 - Update fr-CA for d2l-outcomes-overall-achievement (20.21.2)

- package-lock.json
Adding all but **Welsh** in case we don't get it by EOD. This at least gets us all languages but **Welsh** updated for `20.21.2`.
Uses: https://github.com/Brightspace/d2l-outcomes-overall-achievement/releases/tag/v1.1.42-20.21.2-hotfix-2
> DE42328 - Update translations for d2l-outcomes-overall-achievement (20.21.2)

- package-lock.json
Activities without start dates were not clickable, this fixes that - see corresponding change in https://github.com/BrightspaceHypermediaComponents/activities/pull/1516
rally ticket: https://rally1.rallydev.com/#/357251704080ud/workviews?Name=Activities%20are%20no%20longer%20clickable%20&Priority=High&Project=%2Fproject%2F357251704080&Requirement=%2Fhierarchicalrequirement%2F459574112788&Severity=Major%20Problem&detail=%2Fdefect%2F499184063304&iteration=u&parentRef=%2Fhierarchicalrequirement%2F459574112788&rankTo=BOTTOM&view=b064b584-6337-43c1-b9a9-28047568284d&fdp=true?fdp=true
> [Cert fix 20.21.3] W2D: Activities w/o start dates

- package-lock.json
- package.json
- rollup/rollup-wc.config.js
[This plugin](https://github.com/rollup/plugins/tree/master/packages/dynamic-import-vars#how-it-works) allows for the use of dynamic `import` statements by replacing variables with glob patterns to find and add files to the build. It then creates a `switch` to handle each case.
> Add support for dynamic imports

- .github/workflows/bsi-update.yml
Going to let this trigger a BSI release this time, and see if the LMS's sync job is also broken.
> Switch back to previous ghworkflow branch name

- oslo/generate-monolith-xml
[DE42251](https://rally1.rallydev.com/#/110294864140d/custom/110851118712?detail=%2Fdefect%2F488586858356&fdp=true?fdp=true) 
I don't fully have this mapped out about what I need to do to make this work end to end, but I know certain steps are necessary to start, this being one of them. Once I get this BSI change in I can start to test how this maps to the lms build with [`Instal-Oslo.ps1`](https://github.com/Brightspace/lms/blob/master/lp/build/Install-Oslo.ps1) as there are already certain components with es-ES enabled in their serge files.
Currently known list of tasks for this defect:
1. Add `es-ES` to the oslo part of BSI (this PR)
2. Add `es-ES` to the relevant serge files in the repos (namely activities, attachments)
3. Update …
> DE42251 Adding es-ES language to the oslo xml file

- oslo/generate-monolith-xml
US126015
- fr-on needs to be added for upcoming fr-on work
- cy-gb, fr-fr exist but haven't been part of oslo until now
- zh-cn should just be zh-cn, not moved to 2 chars (this doesn't actually change anything functionally, but brings us in line with how the fallbacks should be working)
> Adding cy-gb, fr-fr, fr-on and updating zh-cn for oslo

- rollup/rollup-wc.config.js
Certain client-side scripts have conditional code/logic keyed off `process.env.NODE_ENV`. Specifically React likes to do this, as does `mobx`.
`mobx` gets pretty cranky if it doesn't see "production" in there... specifically it's getting `undefined`, so it complains thus:
> [mobx] you are running a minified build, but 'process.env.NODE_ENV' was not set to 'production' in your bundler. This results in an unnecessarily large and slow bundle
Looking for `process.env.NODE_ENV` is so common that the [replace Rollup plugin](https://github.com/rollup/plugins/tree/master/packages/replace#usage) uses this as its main example for using it. So this is the approach I've taken to address it.
While I was in here, I noticed warnings about the `preventAssignment` option soon defaulting to `true` and we …
> handle scripts trying to access process.env.NODE_ENV, specifically mobx

- package-lock.json
This adds the [changes from this PR](https://github.com/BrightspaceUI/table/pull/227) to fix an issue with column overlap in sticky headers in the cert stage of `20.21.4`.
> upgrading table to 2.4.4 to pick up fix for sticky headers

- package-lock.json
Manually bumping BSI for certfix. Should now be pointing to this commit: https://github.com/BrightspaceHypermediaComponents/activities/commit/aabd3bd4fb80c006da0cfb3a958b359ba172e2f7
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F514561889664
> Bumped activities for certfix

- web-components/d2l-table.js
As per [this change](https://github.com/BrightspaceUI/table/pull/233), `-10px` is now the default so no need for this code.
> removing offset now that -10 is the default

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/releases/tag/v1.115.2
> bump ce to 1.115.2

- package-lock.json
This cert fixes the grades sticky header issue. Technically the core change isn't needed since our numeric-input web component flag isn't on, but it's not doing anything.
> upgrading core and table for sticky headers fix

- rollup/rollup-wc.config.js
[US123773](https://rally1.rallydev.com/#/357252275780d/custom/367300408400?detail=%2Fuserstory%2F480102056300&fdp=true?fdp=true)
Replacing the `discover-sample-button` with the `discover-rules` component.
> Replacing the erroneous sample button with the actual rule component

- package-lock.json
- package.json
I... Don't entirely know if I've done this right, so if I haven't please feel free to yell at me. The editor needed to be hotfixed to include a fix to ISF (https://github.com/BrightspaceUI/htmleditor/pull/155).
This also contains two unrelated commits (1.4 and 1.5 of the editor respectively) that have the net result of introducing a new API. This shouldn't impact existing apps, but would let us backport an LMS-side fix that would need to use this new API if it turns out this is necessary. I would rather just bundle the changes together and get away with one BSI release as opposed to having to do another one later if it turns out we need to backport the API changes after all. If others disagree I'm open to changing this.
> DE43118 - Update BSI to use hotfixed version of the HTML editor component

- package-lock.json
- package.json
Didn't quite make branching on this HTML editor change last week. For reference, this is what we're backporting: https://github.com/BrightspaceUI/htmleditor/compare/v1.7.6...v1.7.7
> Bump htmleditor version in cert (contains % height fix)

- package-lock.json
This includes the fixes for [DE42852](https://rally1.rallydev.com/#/357252275780d/custom/367300408400?detail=%2Fdefect%2F510897356476)
Tested before and after updating package lock by using `npm ci` to confirm the changes take place as expected
> [Cert] Update discover-fra to v3.1.3

- package-lock.json
Change comparison: https://github.com/BrightspaceUI/htmleditor/compare/v1.7.7...v1.7.9
The 20.21.5 version of BSI is already looking for version ~1.7 of the editor so only the package lock needs changing here.
> Backport htmleditor a11y fixes, eqn editor fix, and translations to 20.21.5

- package-lock.json
- package.json
- rollup/rollup-wc.config.js
Incremented the package version in the insights-engagement-dashboard and was able to remove all references to button-group in the package-lock. I think this is gone forever. 😄
> Remove references to button-group

- package-lock.json
Picks up changes needed for feature flagging some existing functionality. This will require 1 more PR on the LMS once the BSI release is made.
> US127501/US127502 - Update to latest d2l-outcomes-overall-achievement (20.21.5)

- package-lock.json
[DE43573](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fdefect%2F604787926432&fdp=true?fdp=true): [cert] Lessons FACE > HTML editor does not load on HTML Topic page
Updating BSI 20.21.6 to be pinned to the latest [Siren SDK]https://github.com/BrightspaceHypermediaComponents/siren-sdk/commits/master) commit
> DE43573 - backporting latest siren SDK commit

- .serge-mapping.json
- package-lock.json
- rollup/rollup-wc.config.js
[US127858](https://rally1.rallydev.com/#/23525809118d/portfolioitemstreegrid?detail=%2Fuserstory%2F603047932448&fdp=true?fdp=true): [AQ] New Temporary Assessment Quality Dashboard Page
PR publishes the dashboard to CDN. It also registers repo for serge translations
FYI @anhill-D2L @hyehayes @johngwilkinson @NicholasHallman @bemailloux
> US127858 [AQ] New Temporary Assessment Quality Dashboard Page. Publish the dashboard to CDN

- package-lock.json
Contains the following changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.7.9...v1.7.10
> Bump htmleditor version to 1.7.10

- package-lock.json
Updating siren-sdk and activities for:
- [DE43588](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F605071055280&fdp=true): Default fonts in new HTML editor needs to be Verdana/Lato
- [DE43500](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F603973776280&fdp=true) FACE HTML > Head scripts are duplicated when saving html files
Using the latest[ commit from `siren-sdk`](https://github.com/BrightspaceHypermediaComponents/siren-sdk/commits/master) 
Using the latest [commit for the 20.21.6 activities release of 3.161.3 ](https://github.com/BrightspaceHypermediaComponents/activities/releases/tag/v3.161.3b)
> Backport activities and siren-sdk commits for html editor

- package-lock.json
- [DE43589](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fdefect%2F605074749528&fdp=true?fdp=true): [cert] FACE HTML > HTML file content saved as "undefined"
- [DE43565](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fdefect%2F604746646724&fdp=true?fdp=true): [cert] Lessons FACE Modules > HTML editor default size is too small
Backporting the fixes for the above 2 defects
Backporting the fixes for the above 2 defects
N/A
- https://github.com/BrightspaceHypermediaComponents/activities/pull/1746
- https://github.com/BrightspaceHypermediaComponents/activities/pull/1741
Update 20.21.6 LMS with the latest 20.21.6 BSI version after this is udpated
> Phoenix html editor backport branch

- package-lock.json
[DE43464](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fdefect%2F603463835080&fdp=true?fdp=true): Work to Do Widget empty state is missing the checklist image on MacOs Safari and mobile browsers
https://github.com/BrightspaceHypermediaComponents/foundation-components/pull/225
> Bump foundation components for CERT

- package-lock.json
- [DE43731](https://rally1.rallydev.com/#/289692574792d/dashboard?detail=%2Fdefect%2F600345601867&fdp=true?fdp=true): FACE HTML > HTML file content saved as "undefined" when using the rich text editor
- [DE43733:](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F600359414369&fdp=true) FACE HTML > clicking 'back' with changes in editor does not trigger discard changes popup
Backporting the fixes for the above 2 defects.
- https://github.com/BrightspaceHypermediaComponents/activities/pull/1756
> Bump activities for html editor fixes

- package-lock.json
Contains the following changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.7.10...v1.7.11
> Bump HTML editor version to 1.7.11

- package-lock.json
Uses release [v3.8.10 (20.21.6 Hotfix 1)](https://github.com/Brightspace/d2l-rubric/releases/tag/v3.8.10-20.21.6-hotfix-1) from [Brightspace/d2l-rubric](https://github.com/Brightspace/d2l-rubric) and release [v3.164.4](https://github.com/BrightspaceHypermediaComponents/activities/releases/tag/v3.164.4) from [BrightspaceHypermediaComponents/activities](https://github.com/BrightspaceHypermediaComponents/activities).
> DE43937 - Backport `fr-ON` changes in `d2l-rubric` and `activities`

- package-lock.json
Rally: [US129073](https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fuserstory%2F601565647541)
Bumps `d2l-rubric` and `BrightspaceHypermediaComponents/consistent-evaluation` to include the feature flag changes for the new inline rubrics revamp.
> [20.21.7] bump rubrics and consistent eval

- package-lock.json
Picking up [this fix](https://github.com/BrightspaceUI/core/pull/1409) for Safari's lack of requestIdleCallback.
> upgrading to core 1.139.3 to pick up rIC Safari fix

- package-lock.json
Picking up [this fix](https://github.com/BrightspaceUI/intl/pull/89) to Intl for cert into 20.21.7.
> intl 3.5.1 picks up Safari fix

- package-lock.json
[DE43998](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fdefect%2F601841380817&fdp=true): [cert] LTI page - Add link to LTI link entity that will check X-Frame-Options header
Updating siren-sdk and activities for the above defect, which relates to user story [US128812](https://rally1.rallydev.com/#/289692574792/custom/355050439968?detail=%2Fuserstory%2F600911792617&fdp=true).
https://github.com/BrightspaceHypermediaComponents/activities/pull/1820
https://github.com/BrightspaceHypermediaComponents/siren-sdk/pull/349
> Bump siren-sdk and activities for DE43998

- package-lock.json
Contains the following changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.11.1...v1.11.3
> Bump HTML editor version to v1.11.3

- sass/deprecated/button.scss
This goes along [with this PR](https://github.com/Brightspace/lms/pull/11189#pullrequestreview-687735335) which brings fullscreen dialogs to MVC.
Dialogs [apply some margins](https://github.com/BrightspaceUI/core/blob/master/components/dialog/dialog-styles.js#L117) to the buttons in the footer. But this CSS we're generating for the monolith sets a margin of `0` on all buttons (and overrides the right margins), which has a higher precedence.
So this re-introduces a copy of it... which I don't love but couldn't think of a better solution.
> reapplying dialog button margins since they get zeroed out

- package-lock.json
Contains these changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.11.3...v1.11.4
Note that the 20.21.6 version of BSI is already pointing at ~1.11, so there's no need to update the package file (just the lock file).
> DE44116 - Bump htmleditor to v1.11.4

- package-lock.json
Update to get latest [v1.225.x](https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/releases/tag/v1.225.2) release of `consistent-evaluation` and the latest release [v3.13.8](https://github.com/Brightspace/d2l-rubric/releases/tag/v3.13.8) of `d2l-rubric`.
> F17579/F17878 - Update BSI

- package-lock.json
- package.json
Contains these changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.14.4...v1.14.9
Translations are finally in, so time to bump the 20.21.7 version of the editor!
> Bump 20.21.7 version of editor to 1.14.9

- package-lock.json
Bump activities to v3.175.2c to bring in 20.21.7 translations
This brings in https://github.com/BrightspaceHypermediaComponents/activities/pull/1845
> DE44180: Bump activities to v3.175.2c

- sass/html-editor/html-editor.scss
We're building validation into the editor component, so we would prefer to suppress the MVC framework's tooltip and rely on the component's form validation instead.
> Suppress MVC framework validation tooltip in LMS (use the editor component's tooltip instead)

- sass/html-editor/html-editor.scss
Need to take a slightly different approach to hide the LMS' validation toolti[ on the new HTML editor, since the CSS approach doesn't work everywhere (specifically, if the editor is embedded in a table this doesn't work as expected).
> Remove CSS targeting LMS validation bubble on HTML editor (change wasn't effective everywhere)

- package-lock.json
The changes are already in 20.20.8. Backporting them to 20.20.7 for an upcoming hotfix.
> DE44358: bump core, mycourses, image-banner in 20.20.7

- package-lock.json
Includes commit https://github.com/BrightspaceUI/core/commit/c0c0f069323f1775fe9198173630c8dec126e5d1.
> DE44538: bump core to 1.150.6 in 20.21.8

- package-lock.json
Contains the following changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.14.9...v1.14.10
The changes not related to the actual emoji dialog were necessary to get semantic-release to work with the default branch renaming. Those won't get pulled into the npm package so won't make their way into BSI.
> Bump HTML editor version to 1.14.10

- package-lock.json
Includes https://github.com/Brightspace/d2l-rubric/pull/928.
> DE44567 - Update `d2l-rubric` (20.21.8/cert)

- package-lock.json
Updating the engagement dashboard for the august release. Includes translations, updates to settings form validation, and updated error states.
> 21.8 Engagment Dashboard Cert Bypass

- package-lock.json
- package.json
Contains the following changes intended for 20.21.8 cert: https://github.com/BrightspaceUI/htmleditor/compare/v1.20.0...v1.20.7
> Bump HTML editor cert release

- package-lock.json
See relevant commit in hmc-foundation components here: https://github.com/BrightspaceHypermediaComponents/foundation-components/commit/b720d76b7d41faa72abedc70848022071a4f1776
Rally defects: https://rally1.rallydev.com/#/357251704080/custom/367300408400?detail=%2Fdefect%2F603778332755
https://rally1.rallydev.com/#/357251704080/custom/367300408400?detail=%2Fdefect%2F603983938391
similar PR incoming for 20.21.7
> fix: Backport DE44343 and DE44396 to 20.21.8

- package-lock.json
Contains these changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.20.7...v1.20.8
> Bump editor to v1.20.8

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/commit/55f4f11a035844c5d7c22a3454edc7041d0a721b
> Backport missing CE TLs to 20.21.8

- package-lock.json
Updating d2l-rubric commit hash with latest hotfix version: https://github.com/Brightspace/d2l-rubric/releases/tag/v3.18.19
Rally ticket: https://rally1.rallydev.com/#/57732444928ud/defects?detail=%2Fdefect%2F606479886631
> Rubric feedback HTML hotfix - DE44765

- package-lock.json
hotfix: Includes [55439d3](https://github.com/Brightspace/d2l-rubric/commit/55439d3ecc5528c9beef35fc46fe830141af98af) via [36fb27b](https://github.com/Brightspace/d2l-rubric/commit/36fb27ba1ad9a7bed7ae5c0c562e71ec73352774)
> DE44817 - Update `d2l-rubric` (20.21.9)

- package-lock.json
Contains these changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.20.9...v1.20.11
The fix in v1.20.10 was never backported into BSI because it's not needed in the core LMS. It's harmless though, so bundling it in here won't cause any issues.
> DE45126 - Bump editor version to 1.20.11 (HTML conversion fix)

- package-lock.json
- package.json
Contains these changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.23.0...v1.23.2
Once again, v1.23.1 contains some misc. changes that shouldn't cause any issues here; just a fix I didn't intend to backport originally, but that certainly can't hurt to backport.
> DE45125 - Bump editor version to 1.23.2 (HTML conversion fix)

- package-lock.json
Contains these changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.23.2...v1.23.3
> Bump HTML editor version (fix head stripping issue)

- .serge-mapping.json
Rally Ticket: https://rally1.rallydev.com/#/289692574792d/custom/355050439968?detail=%2Fuserstory%2F609020545979
Adding the path to the serge config for Sequences will allow the OSLO langterms to show up on the LMS during a build (through BSI)
> US131626: LX (Sequences) > OSLO > Get OSLO langterm build scripts working for BSI

- package-lock.json
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fdefect%2F609569756647
> DE45250 Hotfix for 20.21.9: Bump @brightspace-ui/htmleditor to 1.23.4

- web-components/d2l-activity-alignments.js
https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fuserstory%2F603437125947
Part of [Brightspace/lms#14424](https://github.com/Brightspace/lms/pull/14424) - avoids extra conversion of `d2l-select-outcomes` and `d2l-alignment-update` in activity alignments
> US129749 - Remove select-outcomes component from BSI

- package-lock.json
Latest `3.x` version: https://github.com/Brightspace/d2l-rubric/releases/tag/v3.24.4
> Update 20.21.10 d2l-rubric with hotfix changes

- package-lock.json
Updating with latest `3.23.x` version: https://github.com/Brightspace/d2l-rubric/releases/tag/v3.23.13
> Update 20.21.9 with d2l-rubric hotfix changes

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/693
> upgrading logging in 20.21.10 to ignore benign errors (#4741)

- package-lock.json
Bump CE for 20.21.10
[PR](https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/695) for reference
> De45341 - bump consistent-eval

- package-lock.json
bump CE in 20.21.9 to get changes from 
posts attached files broken link - [PR](https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/694)
update overall grade on rubric save - [PR](https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/696)
> bump consistent eval

- package-lock.json
[DE45729 - 20.21.11 Discussions/New Evaluation Experience >Inserted MathML equations does not display while assessing the students post using New Evaluation Experience](https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fdefect%2F612634991443)
> DE45729 - CE - Backporting DE45435 (MathML equation fix) to 20.21.11

- package-lock.json
Backport the fix in https://github.com/BrightspaceHypermediaComponents/foundation-components/pull/340 to `20.21.11`.
See tickets: 
- [DE45912](https://rally1.rallydev.com/#/?detail=/defect/610442836939&fdp=true): (20.21.11) Work To Do Widget > 20.21.9 > Widget items showing early due date after Daylight Savings Time (Nov 7)
- [DE45455](https://rally1.rallydev.com/#/?detail=/defect/610442836939&fdp=true): Work To Do Widget > 20.21.9 > Widget items showing early due date after Daylight Savings Time (Nov 7)
Also, related slack thread: https://d2l.slack.com/archives/C02HQ2QDZLM/p1636042049216300?thread_ts=1635968795.201400&cid=C02HQ2QDZLM
- Update `package-lock` to point to the release commit: https://github.com/BrightspaceHypermediaComponents/foundation-components/tree/release/0.56.x
None.
> DE45912 backport

- package-lock.json
Contains these changes: https://github.com/Brightspace/ifrau/compare/v0.39.3...v0.39.4
> Bump ifrau version in BSI (fix fullscreen bug in FRAs)

- package-lock.json
Update to v.1.0.27: https://github.com/Brightspace/module-scheduler/commit/31e6126d0955d070d13020cfc11411f609a046ac
Includes module-scheduler changes:
- Tags UI for Module Ignore Strings 
- Minor text update in Ignore List confirmation dialog
> Bump module scheduler to v.1.0.27

- package-lock.json
Update to v.1.0.31: https://github.com/Brightspace/module-scheduler/commit/40a4af452b5b43fe3c07869170d8e3c71c1f788c
Includes module-scheduler change for Fetching All Semesters
> Bump module-scheduler to v.1.0.31

- package-lock.json
Bump Sequences from 
V2.37.0: https://github.com/BrightspaceHypermediaComponents/sequences/releases/tag/v2.37.0 
to V2.37.2 (translations backport): https://github.com/BrightspaceHypermediaComponents/sequences/releases/tag/v2.37.2,
which also includes changes from
V2.37.1 (defect fix): https://github.com/BrightspaceHypermediaComponents/sequences/releases/tag/v2.37.1
> DE46051: [cert] LX > Expand/collapse button in wrong position after expanding
