- bower.json
- src/grid.scss
tables now follow the selected active and active-selected pattern for highlighting rows
> Updated legacy tables

- src/page.scss
Removing the min-width we apply to the page to allow for responsiveness.
@d2l-joelp: here you go!
> removing min-width

- src/grid.scss
Improve css targeting of last row to only capture td and th that are direct children.
> Grid lastrow

- src/dialog.scss
Adding position fixed for dialog on small screens, prevent scrolling away. iframe width grows to the container.
> US67576 Responsive dialog improvements

- src/bsi.scss
- src/shim.scss
@rylan @dlockhart @dbatiste @capajon adding shim styles to BSI.
> US68431: Add Daylight-specific shim styles.

- bower.json
- src/bsi-style.html
@dbatiste 
Is there anything else that needs to be updated?
> Adding vui-link web component

- bower.json
- package.json
- src/bsi.html
> adding first iteration of navigation web component

- src/page.scss
Daylight bug bash story:
https://rally1.rallydev.com/#/15545167705d/detail/userstory/49673235406
I went through several pages to see if I needed to adjust any other special cases.  I didn't find any but please let me know if you are aware of any.
@dlockhart 
I'll probably wait to do a release/update the LMS BSI config file, so I'm not doing one per story - probably do it daily rather than per 'bash story'.
> Change background to white

- src/bsi.scss
- src/html-editor.scss
Will be updated with more details.
Related PR: https://git.dev.d2l/projects/CORE/repos/lp/pull-requests/2428/overview
> Us69647 html editor daylight off

- bsi-style.html
- html-editor.html
- htmleditor.html
Will be updated with more details.
Related PR:
LE: https://git.dev.d2l/projects/CORE/repos/lp/pull-requests/2428/overview
> Us69647 html editor

- src/bsi.scss
- src/dialog.scss
> Dialog styles from le daylight off

- src/dialog.scss
2/3 PRs
- Brought in all styles from LE dialog.css file
- Removed .daylight from any selectors
- Merged selectors when possible
- I reordered some selectors to have similar things near each other - not sure if we go pure alphabetical or really care about selector order (of course selector order can be very significant in CSS but I didn't think anything here was depending on selector order)
@dbatiste
> Moving common (daylight on or off) styles from LE to BSI

- src/page.scss
This reverts commit 758229993555f7599da8bef077c0563638c22210.
> Revert "Revert "US687373: Add a margin below the header.""

- src/page.scss
> Page margin more fluid and in line with daylight grid design

- bower.json
> Update d2l-my-courses to v0.2.1

- src/context-menu.scss
US70736 - [UI] Hide Collapse this Widget
https://rally1.rallydev.com/#/51191528503d/detail/userstory/55021256329
Will not have any effect until PR#2586 in merged in the LP.
> Fix context menu rendering issue when menu has hidden items

- bower.json
Includes fixes for missing style includes. (see https://github.com/Brightspace/d2l-my-courses-ui/pull/32)
> Update to d2l-my-courses v0.3.1

- src/dialog.scss
@dlockhart Hoping this small change makes the BSI release today.
This is for https://rally1.rallydev.com/#/25052610463d/detail/defect/54447030760
It does help there.  However, I am worried that I am breaking other dialog stuff by removing it.  I am trying various dialogs out though, including on mobile, and it seems okay so far.  So I don't know.  Dialogs are a  bit fragile atm.
> Adjusting dialog height in daylight

- bower.json
Filters out any courses marked as `inactive`.
> Update to d2l-my-courses v0.4.0

- bower.json
Includes switch to use Hypermedia APIs on the LMS
> Update d2l-my-courses to v0.8.0

- bower.json
- bsi.html
- src/deprecated/loadingSpinner.css.scss
- src/deprecated/loadingSpinner.scss
- src/dialog.scss
- src/vui.scss
> Upgrading to d2l-loading-spinner 3.0.0 and deprecating vui-loading-spinner

- bower.json
Updating dependency on icons repo to automatically pull in minor version bumps: Typically adding new icons. Also resolve the icons repo to the latest version to avoid version conflicts with dependencies.
> US72882: Update icons dependency to include a few more icons.

- bower.json
Calls enrollments API with `sortBy=pinned` to get all pinned courses first
> Update d2l-my-courses-ui to v0.10.1

- bower.json
Includes overflow menu on course tiles with pin/unpin and change course image option
> Update my-courses to 0.13.0

- src/page-two-panel-selector.scss
> fix selections for responsive twopaneselector

- src/page-two-panel-selector.scss
> Change background of two panel separator on mobile responsive layouts

- src/page-two-panel-selector.scss
@capajon This styles the 2PS separator and fixes its position at the top in desktop.
> US77141: Add styles for supporting animated scroll in a 2PS.

- src/page-two-panel-selector.scss
Follow-up to https://git.dev.d2l/projects/CORE/repos/le/pull-requests/5841/overview
> US77508: Shrink sidebar in 2PS down.

- bower.json
Includes a whole bunch of changes, hadn't done a release in a while apparently.
> Update to d2l-my-courses 0.14.0

- bower.json
This has some upgrades, but mostly fixes not being able to launch the "change image" ui
> bump d2l-my-courses to 0.15.3

- bower.json
https://travis-ci.org/Brightspace/d2l-my-courses-ui/builds/171106446
> bump d2l-my-courses to v0.15.4

- bsi.html
- src/index.js
@dlockhart : this is the change to load d2l-performance from bsi.js.
> Move the performance include to bsi.js.

- bower.json
d2l-menu version change caused a break, fixed in this.
> Update My Courses

- bower.json
Includes latest d2l-page-load-progress.
> Update to latest d2l-navigation.

- bower.json
https://github.com/Brightspace/brightspace-integration/pull/351
> Bump d2l-button-group

- bsi.html
- d2l-navigation.html
- package.json
@dbatiste I'm going to feature flag the conversion of the navigation component to server-side rendering. This will let us conditionally include navigation's web components in the meantime.
> breaking out navigation into its own shard in preparation for its removal

- src/navigation/personal-menu.scss
@dbatiste your suggestion worked, need to make these changes though
> switching personal menu to use d2l-icon

- bower.json
Bump `d2l-my-courses` to v0.21.0
> Bump d2l-my-courses to v0.21.0

- src/page-two-panel-selector.scss
Tools/Pages using Two Panel Selector 
- Discussions
- User Progress
- Content
- Media?
> by default reduce side panel width

- bower.json
I would like this one to be tested in the LMS before releasing.
This change affects (or rather SHOULDN'T affect visually) tables with actions and user grade submission page (instructor view)
> Bump button group

- bower.json
Bring my courses to latest version.
Includes bug fixes and new features
> Bump my courses to newest version

- src/deprecated/table.scss
~35% improvement for every style calculation
On the user_list_view.d2l page with 100 users displayed and 3 grades +1 final grade
Before: 19.97s
After: 18.81s
> (perf) Replace >:last-child,>:first-child,>:only-child

- src/grid.scss
Another ~12% off style calc time in Edge/IE
> Replace more :*-child

- src/navigation/common.scss
- src/navigation/header.scss
- src/navigation/mobile-menu.scss
I also changed the breakpoint variable names a bit.  Probably should have done that separately after, sorry.
> De23947 responsive dividers nav

- src/deprecated/icons.scss
@dlockhart I'm not sure what the status of the icons are. How are they used in customizations? Do I need to add a `.d2l-icon-custom` selector as well? (For buttons)
> Remove expensive selector for IE11/Edge

- src/navigation/logo.scss
- src/navigation/mobile-menu.scss
Fix the highlight-bar is positioned lower when turn off branding flag.
Use inline-flex instead of flex for logo
> De23098 logo focus for branding off

- bower.json
- package.json
- src/navigation/admin-menu.scss
- src/navigation/common.scss
- src/navigation/course-menu.scss
- src/navigation/header-course.scss
- src/navigation/header.scss
- src/navigation/logo.scss
- src/navigation/main.scss
- src/navigation/mobile-menu.scss
- src/navigation/notifications.scss
- src/navigation/personal-menu.scss
- src/page-two-panel-selector.scss
- src/page.scss
- typography.html
The cases in the SCSS files weren't an issue for some reason (likely we're using an older version of clean-css), but I fixed them up anyway.
> space is required otherwise clean-css causes trouble

- bower.json
- d2l-image-banner-overlay.html
- package.json
Waiting on: https://github.com/Brightspace/d2l-image-banner-overlay/pull/1
> add the image banner overlay to bsi

- bower.json
Contains updated fastdom-import
> bump more-less

- bsi.html
- src/index.js
- src/page-loading/page-loading.js
- src/page-loading/web-components-ready.js
I just noticed telemetry wasn't being reported for IE11 with daylight on. This fixes it.
> Fix d2l.page.load event not being measured in IE11

- package.json
This just like... isn't true, right? And not needed? (not a big deal, at worst it's just slightly confusing)
> Remove package.json version

- bower_components/d2l-my-courses/d2l-course-tile-sliding-grid-behavior-utility.js
- bower_components/d2l-my-courses/d2l-course-tile-sliding-grid-behavior.html
No idea why these didn't show up... absolutely none. But hey, they're added now.
> Where did sliding tile behavior go?

- bower.json
Was causing BSI to be all "idk which version tho".
> Tilde d2l-alert

- bower.json
- bower_components/d2l-my-courses/.bower.json
- bower_components/d2l-my-courses/d2l-course-tile-sliding-grid-behavior.html
Includes CSS animation fixes from https://github.com/Brightspace/d2l-my-courses-ui/pull/341
> Bump My Courses

- bower.json
Hopefully the last of the typography references.
> upgrade to my courses 1.2.8

- bower.json
- src/deprecated/table.scss
* font-size
* font-weight
* cell padding
* letter spacing
> Grid style updates.

- src/page-loading/page-loading.js
PR to Brightspace coming to update daylight-off BSI release.
> new server, download and visible timings in daylight-off branch

- bower.json
- web-components/button-menu.html
Will do the following before merge (From @dlockhart )
1.Do a minor release of the button component (after all your changes are merged)
2.Upgrade the bower.json file in this PR to pull it in
> De23228 button focus style

- bower.json
Removes dependency on d2l-siren-parser-ui
> Bump d2l-my-courses

- bsi.html
- d2l-more-less.html
- polymer-build.js
Going to also do d2l-table, but separately.
> Pulling out the more/less component into its own import

- sass/common.scss
- sass/navigation/common.scss
- sass/page-two-panel-selector.scss
- sass/page.scss
We noticed in email, after setting it to full width, that the page padding gets a little too generous at very wide viewports.  I believe this should be a pretty safe change.
> Adding max left and right page padding

- sass/navigation/index.scss
- sass/navigation/main-image-based.scss
This PR adds some basic styles to get started on image-based nav.
> Adding initial styles for basic alternate link-area rendering.

- sass/navigation/main-image-based.scss
Crop using the smallest dimension, and cover using the result.
> Image-based nav - crop images.

- sass/dialog.scss
Will add comments to related LMS PR.
> Fix for dialogs scrolling out of view when inputs are used on ios

- nav-icons/competencies.svg
- nav-icons/dropbox.svg
Updated dropbox.svg and added competencies.svg
> US88483-add and update svgs

- src/page-loading/page-loading.js
`v.10.6.12-daylight-off` was created from `v.10.6.11-2` tag
> Added metrics of Google Analytics to daylight-off version for 10.6.12

- bower.json
- d2l-navigation.html
- polymer-build.js
See platformTools#1675
"Tangentially related to US88653 and US88649"
> remove d2l-navigation webcomponent

- bsi.html
Now that the navigation WC isn't doing it for us.
> DE27104: explicitly importing menu-item-link

- bower.json
- d2l-activity-exemptions.html
- polymer-build.js
- Use d2l-my-courses-ui as a pattern for integrating into bsi
> Add reference to activity-exemptions

- .travis.yml
@RyanSweetD2L FYI, if this works in `master` you can likely do the same in `daylight-off`.
> switching back to latest node now that node-sass binaries are available

- bower.json
> DE27574/DE27575 - Update My Courses

- js/page-loading/web-components-ready.js
This is another attempt to fix the sporadic errors we're seeing during UI automation. The error we're getting is this one:
> Uncaught DOMException: Failed to execute 'measure' on 'Performance': 'responseEnd' is empty: either the event hasn't happened yet, or it would provide cross-origin timing information.
That's thrown from Blink's code -- [here's a test exposing the behaviour](https://github.com/primiano/blink-gitcs/blob/master/LayoutTests/fast/performance/performance-measure-exceptions.html#L28).
The theory is that our measurement of `d2l.page.visible` -- which uses `responseEnd` as a starting point is firing _before_ the `responseEnd` mark actually occurs. This could be possible if Chrome is doing crazy optimizations somehow.
The fix is to wait until both the `WebComponentsReady` AND …
> not measuring page events until WC-ready and page load event have fired

- sass/navigation/main-image-based.scss
Leaving old class names here until refactoring in the LMS is complete.
> Updating image-based icon class names to support refactoring.

- bower.json
Contains fix to `d2l-alert` event names
> DE28347 Update d2l-image-banner-overlay

- bower.json
Nothing particularly exciting, just some minor refactoring and adding tests
> Another banner update

- build-email-icons.js
...Ensure rejected promise results in failure exit code
> Place email icons in images subfolder

- build-email-icons.js
Probably better to just convert all icons automatically so forgetfulness doesn't bite me, but for now..
> Add image icon

- bower.json
This release includes the new My Courses features using an updated sort, filling to 12 courses and a new unified all courses view
> Update bower.json to include new My Courses

- bower.json
Mostly just refactors and new tests.
> Update My Courses to 3.0.1

- bower.json
Contains My Courses translations
> Update bower.json for My Courses release (v3.3.3)

- bower-locker.bower.json
- bower.json
- js/index.js
- sass/vui.scss
The feature flag was removed from code in the LMS in `10.7.6`.
> no longer bundling vui-more-less 

- bower-locker.bower.json
- bower.json
- js/index.js
Same change but applied to the `daylight-off` branch.
> removing inclusion of telemetry

- .eslintrc
- js/page-loading/performance-timings.js
- js/page-loading/timing-debug.js
Initial testing shows this working with the `timingdebug` parameter (I don't have @dlockhart's LE changes in yet to test the full flow), but wanted to get this up early to see if this was what you guys had in mind.  It didn't feel like a `measure`, but let me know if I misunderstand how I was supposed to use that.
> Adding Paint Perf Metrics

- js/index.js
- package-lock.json
- package.json
- rollup.config.js
| File | daylight-off | Rollup (% daylight-off) | Rollup & Uglify3 (% daylight-off) |
| ----- | --------- | -------- | ---------------------- |
| bsi.js | 84706 | 97758 (115) | 97758 (115) | 
| bsi.js.gz | 15143 | 19115 (126) | 19115 (126) |
| bsi.min.js | 65660 | 60859 (93) | 60300 (92) |
| bsi.min.js.gz | 14124 | 13782 (98) | 13506 (96) |
> Smaller bsijs bundle nightlight

- package.json
- polymer.json
And here's the same change applied to `daylight-off-polymer-2`.
> Transpiling to ES5

- sass/homepages/homepages.scss
Alex wants "margins between widgets will be reduced from 40px to 30px", the change reflects that.
> US96404-readjusting padding between widgets

- bower-locker.bower.json
- bower.json
gets in the subtle button rtl fix and h-align
> bump button version

- sass/html-editor/html-editor.scss
- sass/html-editor/menu.scss
Improvement over https://git.dev.d2l/projects/CORE/repos/le/pull-requests/11185
> DE30741: fix MenuFlyout position

- web-components/bsi.html
@danyakarras FYI, realized I forgot to actually add `d2l-save-status` to the `bsi.html` import!
> adding save-status import

- README.md
Based on my recent learning thanks to Edward's PR 😄
> Update readme to include instructions on bumping the LP version of BSI

- bower.json
Pointing at master branch for now until it is ready to be versioned
> Add d2l-release-conditions as a bower component

- bower-locker.bower.json
- bower.json
Adds support for cross-origin domains, by trying to fetch them relatively.
> DE31016 Update My Courses

- bower-locker.bower.json
- bower.json
(Sortable just moves, it's not removed)
> Update rubric to 0.106.0

- bower-locker.bower.json
- DE28903
The d2l-my-courses was already automatically updated from another PR. I would like to reflect the version in the bower lock file to stay consistent with build 10.8.6
> Update d2l my courses.

- bower-locker.bower.json
- bower.json
DE28903
There was a problem with the last fix for this DE28903. (Found before merged into the LE) This PR fixes it! :)
> BSI Update for d2l-my-courses (10.8.6)

- bower-locker.bower.json
- bower.json
> BSI Update for d2l-my-courses

- bower-locker.bower.json
- bower.json
Added version 5.7.21 - the alert fix and 5.7.22 - adding serge for d2l-my-courses.
> D2l My courses version 21 and 22

- bower-locker.bower.json
- bower.json
> Enrollment Cards Update for 10.8.7

- README.md
Original post:
"summary from above thread :slightly_smiling_face: if you make a PR that bumps the BSI version past another open PR (that also bumped the BSI version) please add the owner of the PR whose version you passed as a reviewer to your PR, and coordinate with them to ensure that any Core LMS PRs corresponding to the BSI changes are accounted for. Thank you!" -- Josh Roach
> Josh Roach made a post on web-platforms, added to readme

- sass/navigation/header.scss
- sass/navigation/main.scss
Realized these needed to be updated as well.
> update navigation scss to reflect new component names

- web-components/bsi.js
Ok, everything _should_ work after this...
> Add import for d2l-navigation-immersive

- package-lock.json
- polymer.json
- web-components/d2l-rubric-editor.js
- web-components/d2l-rubric-structure-editor.js
- web-components/d2l-rubric.js
Fixed in d2l-html-editor: https://github.com/Brightspace/d2l-html-editor/pull/175/files
> Add back rubrics

- package-lock.json
- package.json
- web-components/bsi.js
Checked commit shas, all looks good
> Add d2l-users and update d2l-icons

- package-lock.json
- sass/navigation/common.scss
- sass/navigation/main-image-based.scss
- sass/navigation/main.scss
- sass/navigation/mobile-menu.scss
Picks up changes to navigation that apply borders to the footer.
FYIs as this pull in various changes to the following:
@jwong-d2l: accordion and sequences
@dbatiste: button
@gfrancu & @mpharoah-d2l: rubrics
@mdgbayly: html-editor
> Refresh from master

- js/d2l-fastdom.js
- js/index.js
- test/fastdom-promised.js
This will let us do things like:
```
D2L.fastdom.measure(() => {
return document.body.offsetHeight;
}).then((bodyHeight) => {
// use bodyHeight somehow
});
```
> integrating fastdom's promise extension

- package-lock.json
- package.json
Now with 100% less NPM version induced suffering!
> Explicitly add d2l-resize-aware to BSI

- package-lock.json
Also a table fix for the "light" style
> Update activities version

- package-lock.json
> update activity alignments

- package-lock.json
> DE33463 -- update d2l-activity-alignments (release branch)

- package-lock.json
- package.json
> Update rubrics; fix d2l-resize-aware source

- package-lock.json
- package.json
> DE33485 -- Bump d2l-rubrics version, fix resize-aware dependency path

- package-lock.json
@mtjandra If you want the translation changes in here too, we can release `activities` and update this PR. Let me know!
> Bump version of activities to 2.4.0

- package-lock.json
Small diff for once :)
https://github.com/BrightspaceHypermediaComponents/activities/releases/tag/v2.12.0
> Bump d2l-activities to 2.12.0

- cli/autotag.js
- package-lock.json
- package.json
`time` was breaking Windows builds.
> switching to use moment instead of time library

- .travis.yml
* Porting fix for build to pass in release branch to allow lang term fixes to come in
* Taken from https://github.com/Brightspace/brightspace-integration/pull/1346
> Lock node version to 11

- package-lock.json
This updates d2l-users and fixes the promise rejection being thrown by simple-cache when fetching the profile image.
> update d2l-users to fix simple-cache

- package-lock.json
New `d2l-activities` version to include the `toggleEnabled` flag on the main component.
> Incrementing d2l-acivities.

- package-lock.json
- sass/deprecated/button-menu.scss
@dbatiste your menu stuff already got in already today.
> picking up button WCAG changes and label updates to typography

- package-lock.json
- polymer.json
- web-components/d2l-enrollment-collection-widget.js
- web-components/d2l-enrollment-summary-view.js
> Learning path homepage widget (My Learnings)

- package-lock.json
- package.json
With the correct commit this time
> DE34415 - Fix Widget Refresh After Change in Settings

- sass/deprecated/list.scss
* update divider styles for selectable/actionable list items per wcag 2.1
* update font for list inside of d2l-dropdown consistent with web components
> Update selectable/actionable list styles per wcag 2.1.

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/activities/releases/tag/v3.1.8
> Bump activities

- package-lock.json
https://rally1.rallydev.com/#/57732444928d/detail/defect/309706009460
https://rally1.rallydev.com/#/57732444928d/detail/defect/310826416212
```
▄▄▄▄     ██████  ██▓
▓█████▄ ▒██    ▒ ▓██▒
▒██▒ ▄██░ ▓██▄   ▒██▒
▒██░█▀    ▒   ██▒░██░
░▓█  ▀█▓▒██████▒▒░██░
░▒▓███▀▒▒ ▒▓▒ ▒ ░░▓  
▒░▒   ░ ░ ░▒  ░ ░ ▒ ░
░    ░ ░  ░  ░   ▒ ░
░            ░   ░  
░              
```
> Cert Fixes: DE34546 and DE34465

- package-lock.json
- sass/deprecated/input-helpers.scss
- bump `d2l-inputs` version
- update transition in deprecated input sass
> inputs: speed up transitions

- package-lock.json
OLD: https://github.com/BrightspaceHypermediaComponents/activities/commit/696dfbc86e493d4a3b1c37dd52fa0edc0e7804d2
NEW: https://github.com/BrightspaceHypermediaComponents/activities/commit/c78ce546699007b5fac9f854432ff69417ec0d00
> Update activities. mostly refactor, some langterms and a loading change

- package-lock.json
OK I built the langterms properly this time
> Update activities with langterms

- package-lock.json
Bump `d2l-search-widget` version in `image-selector` and `my-courses`
> US107582 - Bump d2l-search-widget

- package-lock.json
- package.json
I would like to get this in the LE in the morning for my testers.
I will also be making a release tonight too.
Major Changes:
My Courses v10
Enrollments v4
Other Changes:
- d2l-alert : "version": "github:BrightspaceUI/alert#99865b2e37626a651c6774994cfb2a0daee3a19e"
- d2l-hierarchical-view: "version": "github:BrightspaceUI/hierarchical-view#add6153368cc36ec31546b03d56bfd5388e0a217"
- d2l-organizations: "version": "github:BrightspaceHypermediaComponents/organizations#e2f21573f79298c9b24ddbab182dff89900d40f6" (My change)
- d2l-progress: "version": "github:BrightspaceUI/progress#8672684b81a3cbadb2826d5339557e8e856ea679"
- d2l-sequence-viewer: "version": "github:Brightspace/d2l-sequence-viewer#3bdb6ea56e43e75353e90fff1d51eb2c327295d2" (Dave's Change)
- d2l-sequences: "version": …
> Update Sequences and My Courses

- package-lock.json
Includes: 
https://rally1.rallydev.com/#/39602890252d/detail/defect/315362259952
https://rally1.rallydev.com/#/39602890252d/detail/defect/315365475580
As well as language terms from organization used in activities.
> Update organization and enrollments.

- package-lock.json
last 2 attempts didn't work :((
> BSI bump again 

- package-lock.json
- web-components/bsi.js
Not sure exactly why there are merge conflicts in the package-lock.json, and whether I should be pushing that file, or how to resolve them. Please let me know!
> add telemetry to BSI

- package-lock.json
> updoot Outcomes User Progress

- web-components/bsi.js
[US108638](https://rally1.rallydev.com/#/detail/userstory/322123650748?fdp=true): [UI / LMS] Ensure that right slot of immersive nav is working as expected
Que the facepalm...
> US108638 - Reference the iterator

- package-lock.json
- web-components/bsi.js
https://github.com/BrightspaceUI/navigation/releases/tag/v3.10.0
> Bump navigation to 3.10.0

- package-lock.json
> primarily bumping activities version

- package-lock.json
This picks up @mdulat's fix to icons, as well as the missing "access-special" icon and icon fill colour removal fix.
> bumping core to 1.0.1

- package-lock.json
- package.json
- polymer.json
- web-components/d2l-program-outcomes-picker.js
> US107618 -- Bring the Program Outcomes Picker into BSI

- package-lock.json
Here's the diff in core between these 2 versions:
https://github.com/BrightspaceUI/core/compare/v1.0.3...v1.2.1
> upgrading to core 1.2.1 to fix icon fill bug

- package-lock.json
- web-components/bsi.js
This allows the LMS to leverage the new dismissible helper in its controls.
> exposing core's dismissible stuff to the LMS

- package-lock.json
updating sequences, sequence navigator and sequence viewer
> DE35658 - updating LX for cert

- package-lock.json
fyi @maboelsoudd2l @dlockhart @wongvincent
> Bumping activiites to 3.45.5

- package-lock.json
> Bumping core

- package.json
- polymer.json
- web-components/d2l-tab-panel.js
- web-components/d2l-tabs.js
Make d2l-tabs available for MVC
> Add d2l-tabs component

- package-lock.json
fyi @dlockhart @m6jones @jwong-d2l @djwester @ChrisKraljevicD2L @qwangd2l
> Bump activities to 3.45.13.

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/activities/releases/tag/v3.45.21
> Bump activities to 3.45.21

- package-lock.json
- Include the `d2l-enrollments-summary-view` CSS styling changes
> Bump the d2l-enrollments version

- README.md
I won't merge this until after I enable the Jenkins jobs (and make sure they are running correctly on the real thing, i.e. master updates). I'll also post to #web-platform channel to let people know of the change.
> US109220 update readme - Jenkins now updates LP

- package-lock.json
> Update program-outcomes-picker to v3.0.1

- package-lock.json
> Bumping activities version to 3.45.29.

- package-lock.json
Some updates from the organizations hm component
> bump organizations

- package-lock.json
FYI
@dbatiste 
@dlockhart 
@xiangqiyan 
@awikkerink
> bumped activities

- package-lock.json
This re-introduces `app-localize-behavior` (unfortunately) as some places still need it for async resource loading.
> updating to latest localize-behavior

- package-lock.json
bump sequence viewer and sequences
> bump sequence viewer and sequences

- package-lock.json
> Bump activities to 3.45.41

- package-lock.json
> Bump d2l-sequence-viewer

- package-lock.json
> bumped d2l-facet-filter-sort

- package-lock.json
> Bump sequences and sequence viewer

- package-lock.json
> Bump sequences, sequence-viewer, sequence-navigator

- package-lock.json
> DE36022: bump d2l-sequence-viewer and d2l-sequence-navigator

- package-lock.json
fyi @DiljotSG @BraydonKains @BhamelinD2L
> bumping activities

- package-lock.json
Main change is the addition of the instructions HTML editor to the Activity Editor.
> US110196 Bump activities

- package-lock.json
> US110914: Bump sequence viewer

- package-lock.json
Fixes change event dispatching in the instructions component of `d2l-activity-assignment-editor`.
> Bump BHC/activities

- package-lock.json
> US105249: bump d2l-sequence-viewer

- package-lock.json
Includes due date editing capabilities in `d2l-activity-assignment-editor`. This relies on `d2l-datetime-picker`, hence the influx of Vaadin dependencies. (`d2l-datetime-picker` is getting replaced sooner rather than later, though, and presumably will no longer rely on Vaadin in the new version.)
> US110582 Update activities

- package-lock.json
Contains the fix from https://github.com/BrightspaceHypermediaComponents/activities/pull/449, which fixes due date format support in FACE.
> US110582 Fixup

- package-lock.json
> Bumping activities to version 3.48.1.

- package-lock.json
fyi @ChrisKraljevicD2L and @ChrisKraljevicD2L
> bumping activities and a whole bunch of babel stuff

- package-lock.json
fyi @ChrisKraljevicD2L @sarahboyd
> Bumping common to 2.10.6.

- package-lock.json
- polymer.json
Includes updates to FACE. In particular, this means updating `polymer.json` here to look for the new language files, which are now JS rather than JSON.
> US111620 Update d2l-activities

- package-lock.json
https://github.com/Brightspace/d2l-rubric/pull/580
> ++d2l-rubric

- package-lock.json
Things were getting out of hand here, so trying to update everything before doing a PR of the D2L changes needed.
> Update third-party dependencies

- package-lock.json
does not contain anyone else's commits except mine
> Update `siren-sdk` and `d2l-organizations`

- web-components/bsi.js
Considering starting to update the places that use iron-a11y-announcer.  There are quite a few however, which could be a big clean-up task to update & test them all. So, my current goal is to get the LMS impl updated.
> Expose the announce method.

- package-lock.json
FYI @dlockhart, @mdgbayly, @BhamelinD2L @wongvincent, @xiangqiyan
> Bumping activities version to 3.50.1

- package-lock.json
fyi @dlockhart @m6jones and myself
> bump activities, core and organizations

- package-lock.json
fyi @dlockhart, @BraydonKains, @m6jones
> Bumping activities to 3.50.23

- web-components/d2l-activity-collections.js
- web-components/d2l-enrollment-collection-widget.js
- Add web-component imports for the Learning Paths `d2l-organization-admin-list` and the `d2l-enrollment-collection-view`
> Add Learning Paths web component imports

- package-lock.json
See https://github.com/BrightspaceHypermediaComponents/activities/pull/536
> US112016 Update activities

- package-lock.json
Adds file upload capability in FACE.
> US112361 Update d2l-activities

- package-lock.json
Bringing in this PR https://github.com/BrightspaceHypermediaComponents/sequences/pull/175
> DE37295 - bump sequences and sequence viewer

- README.md
- unbundle-script/unbundle.py
I am just adding a shortcut for the --component-path flag.
> adding -cp flag shortcut for required component path

- es-dev-server.config.js
- package.json
This PR updates the `es-dev-server` configuration to work with the breaking changes in the version we recently updated to...
> Update es-dev-server configuration

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/activities/compare/47adb92a4cccee7923a457cc8ed63c016a8722d3...d80dc25493c413a47e503fe920c6e6d091ce4461
@mdulat adding you as reviewer as your changes are in this release as well
> Update activities to 3.50.70

- package-lock.json
Updates the activity editor to be support audio note attachments.
Also includes a bunch of updates to Babel, apparently.
> US111909 Update activities and siren-sdk

- package-lock.json
Somehow I managed to include an old version in #1820; this includes the most up-to-date `d2l-activities`, along with some other bumps.
> US111909 Properly update d2l-activities

- polymer.json
Add d2l-enrollment-collection-view lang files as a polymer extra dependency so that they get bundled.
> d2l-enrollment-collection-view lang files

- package-lock.json
Fixes the icon used for audio notes in the activity editor.
> US111909 Fixup

- package-lock.json
FYI @mdulat, @ChrisKraljevicD2L, @AllanKerr
> Bumping core version to 1.29.0

- package-lock.json
bumping againnn
https://github.com/Brightspace/d2l-sequence-viewer/releases/tag/v1.5.6
> bump sequence viewer version

- package-lock.json
Bump d2l-activities, d2l-enrollments, and d2l-organizations to include the translated lang terms.
> Backport Hypermedia Component Translations

- package-lock.json
> DE37276 -- Update d2l-rubric

- package-lock.json
- package.json
- polymer.json
- web-components/d2l-content-store.js
Adding https://github.com/Brightspace/d2l-content-store to BSI.
> Adding Brightspace/d2l-content-store to BSI.

- package-lock.json
This component was moved to the Labs organization, and this picks up changes to rubrics and sequences to use that new version.
> using the labs version of accordion

- package-lock.json
- sass/deprecated/button.scss
corresponding changes to https://github.com/BrightspaceUI/core/pull/379/
> updated button styles to match design.d2l

- package-lock.json
- package.json
- polymer.json
- web-components/d2l-user-feedback.js
Adding component github.com/BrightspaceUILabs/user-feedback for using like web-components for feedback dialog from MVC page (according to US111466).
> Adding user-feedback to BSI

- package-lock.json
- polymer.json
Bumping CPD to release 1.1.7
This release features the changes to logo loading on the report
> Bumped cpd, removed logo from build since it is no longer needed

- package-lock.json
https://github.com/Brightspace/d2l-rubric/commit/8777e25a2bc2f614a269cab1af61bff3f13b238e
> Bump d2l-rubric

- package-lock.json
> bump sequence viewer

- package-lock.json
> Update d2l-activities to 3.52.66

- README.md
> Update readme to state that the trailing slash

- package-lock.json
Putting it in the right branch!
This is my first time doing a backport like this so please let me know if there's an issue with the way I'm doing it.
> Bumping d2l-cpd to latest version for 20.20.3

- package-lock.json
> DE38061: bumping sequences

- package-lock.json
- polymer.json
Updated package-lock in the process
> Add awards leaderboard images

- package-lock.json
bumping sequences and sequence viewer to get our download/print fix into cert
> DE38110: bump sequences and sequence viewer

- package-lock.json
**Quality**
Changes have been tested with a local LE instance
> Bumping organizations

- package-lock.json
- package.json
Bump the version in master too as the picker is in the master branch already
> DE38224 - Bump d2l-activity-alignments - 20.20.5

- package-lock.json
@m6jones 
@sarahboyd 
Fixes defects [DE37671](https://rally1.rallydev.com/#/detail/defect/366099331828?fdp=true) and [DE37663](https://rally1.rallydev.com/#/detail/defect/366055406204?fdp=true)
Tested changes locally.
> Bumping enrollments and sequences

- package-lock.json
Fix the latest UMD time bomb explosion
> Use D2L's sortablejs fork to de-umd-ify

- package-lock.json
DE37617
https://rally1.rallydev.com/#/357252966636d/detail/defect/365347773396
> SirenSdk update.

- package-lock.json
Bringing in https://github.com/BrightspaceHypermediaComponents/sequences/pull/212 for DE38306
> bumping sequences and sequence viewer

- package-lock.json
Bringing in v1.5.16 for DE38307
> update sequences for cert

- package-lock.json
- package.json
https://rally1.rallydev.com/#/29180338367d/detail/defect/387521069496
> DE38817 Cert: Update core to 1.43.4 to include template width fix

- package-lock.json
Also bumping `core`, `d2l-organizations` and`d2l-enrollments`
> US115271 - DE38877 - Bump my-courses version

- package-lock.json
> Awards Leaderboard - Version bump

- package-lock.json
This PR is for merging into the `20.20.6` branch
> 20.20.6 - Updated activities to v3.52.193

- web-components/bsi-unbundled.js
- web-components/bsi.js
This is a temporary measure to allow us to start testing and enabling the unbundled BSI builds sooner.
Once this goes in, I'll be able to go back to slowly unbundling each of these one by by, but in the meantime unbundled builds will be functional. 🎉
> temporarily bringing assets into unbundled build

- package-lock.json
Pulling in new versions of dependencies, specifically sequences, sequence-viewer, organizations and enrollments
> Bump sequences, sequence-viewer, organizations, enrollments, etc.

- package-lock.json
https://rally1.rallydev.com/#/29180338367d/detail/defect/395087059664
> DE39328 Bump d2l-activities for 20.20.6 translations

- README.md
- unbundle-script/unbundle-tests.py
- unbundle-script/unbundle.py
Corresponding PR in the monolith:
https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/12152/overview
> renaming "polymer-3" to "endpoint" in BSI config

- sass/navigation/personal-menu.scss
Cleaning up some CSS that isn't needed now that this flag is gone:
https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/12276/overview
> removing some unused CSS

- rollup/rollup-wc.config.js
- web-components/bsi-unbundled.js
- web-components/bsi.js
Goes along with [this LMS change](https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/12282/overview).
> making profile image unbundled

- package-lock.json
- package.json
Not sure why we weren't already using v2, it's fully supported by the open-wc stuff.
> upgrading to rollup v2

- .travis.yml
- README.md
- package-lock.json
- package.json
🎉  Thanks @svanherk for the assist on this one!
> removing dependance on NPM 6.8

- package-lock.json
Only doing my-courses since we're so close to release
> Bump my-courses version

- .github/workflows/scripts/get-app-token.sh
- .github/workflows/scripts/get-jwt.sh
- .github/workflows/trigger-lms-sync.yml
Try getting script files into master
> Us117758 bsisync

- package-lock.json
https://github.com/BrightspaceUILabs/multi-select/commits/master
> Update multi-select to 3.2.2

- package-lock.json
Update d2l-video component and sequences version so updated video component works in BSI
> update sequences and d2l-video

- package-lock.json
To pick up the fix to the breadcrumbs.
> upgrading core

- package-lock.json
- polymer.json
- rollup/rollup-wc.config.js
Fixes issues in legacy-Edge loading lang terms. I'll put this into the `20.20.8` branch as well.
> upgrading edit-in-place

- package-lock.json
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F405070209580
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F406343628716
> DE39807 DE39837 Cert 20.20.8: Bump d2l-activities

- package-lock.json
Context:
DE39804
Fix broken langs for d2l-activity-collection-editor
FYI @patel-kajal Your changes are in as well.
> Activitites bump

- sass/navigation/common.scss
- sass/navigation/main.scss
> DE39554 certfix for 20.20.8

- .serge-mapping.json
- package-lock.json
Adding Teacher Course Creation to serge mapping.
~~NOTE: The file is not currently merged in the `custom-teacher-course-creation` repo, so that should be merged and released first.~~
> US113777 - adding tcc to serge mapping

- package-lock.json
Fixes a defect in award leaderboard tool and possibly others using the `d2l-list-item` component
> 20.20.8 - Updating core to patch release

- package-lock.json
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=%2Fdefect%2F407012271644
> DE39903 Cert 20.20.8: Bump d2l-activities for translation update

- package-lock.json
including a page to handle errors on the TCC admin page
> US116068 including a page to handle errors on the TCC admin page

- package-lock.json
Bump my-courses and a few other repos
> Update my-courses langterms

- package-lock.json
Mostly wanted to pick up the new polymer-behaviours. Trying to avoid conflicts with @kieranderson's open PR.
> updating deps

- package-lock.json
Bump `d2l-facet-filter-sort`, `d2l-common`, `d2l-activities` and `d2l-my-courses`
> US114854 - US114855 - Get BSI using the latest facet-filter-sort

- package-lock.json
- package.json
- rollup/rollup-wc.config.js
- web-components/intl-messageformat-parser.js
[US114902](https://rally1.rallydev.com/#/detail/userstory/378217884416)
Expose a file in BSI that imports the intl-messageformat-parser at runtime and then installs it on a global so that we can reference is in the monolith
We want to use this library to validate ICU Message input fields on the Manage Language page
> expose a file on BSI that imports the intl-messageformat-parser

- package-lock.json
- package.json
- rollup/rollup-wc.config.js
For use in the upcoming Insights Engagement Dashboard.
FYI @anhill-D2L @johngwilkinson @Vitalii-Misechko @rohitvinnakota
> Add brightspace-ui-labs pagination component

- package-lock.json
> upgrading button-group (20.20.9 version)

- package-lock.json
See https://github.com/BrightspaceUI/core/pull/805
Tested with BSI prod build and local LMS
> Bump core 20.20.9

- package-lock.json
> bump activities version

- package-lock.json
Master PR equivalent of https://github.com/Brightspace/brightspace-integration/pull/2418
> Bump intl library

- package-lock.json
Tested with local lms
https://github.com/Brightspace/course-image/pull/37
> update course image version

- web-components/bsi-unbundled.js
Only about 3 weeks in the making haha...
> unbundling menu

- package-lock.json
[US120105](https://rally1.rallydev.com/#/detail/userstory/423713253452/tasks?fdp=true): Handle undefined href initialization on activity editors
https://rally1.rallydev.com/#/detail/userstory/423713253452/tasks?fdp=true
> Bump d2l-activities version for US120105

- package-lock.json
https://rally1.rallydev.com/#/detail/userstory/423726609188?fdp=true
> Bump d2l-activities for US120115

- package-lock.json
https://rally1.rallydev.com/#/detail/userstory/423713941720?fdp=true
> Bump d2l-activities for US120106

- package-lock.json
bump for this pr: https://github.com/BrightspaceHypermediaComponents/sequences/pull/269
> bump sequences

- package-lock.json
https://rally1.rallydev.com/#/detail/userstory/423713941720?fdp=true
> US120106 set assignment editor footer to display normally

- package-lock.json
From this PR that I merged. https://github.com/Brightspace/d2l-rubric/commit/c90f147c60670b36d4a9bbc1dc642de92dc32751
> Updating rubrics version

- package-lock.json
Get the filter changes into `20.20.10`
> [20.20.10] US114856 - DE36186 - Bump my-courses version

- package-lock.json
DE40540 - [cert] Cannot remove attached rubric
> [cert] Update activities

- .github/workflows/bsi-update.yml
Uses https://github.com/Brightspace/lms/blob/master/.github/workflows/bsi-sync.yml as inspiration.  Still need to setup secrets, and for now the job runs on demand, not on a schedule.  I'm also not confident in my syntax, but I believe I need to merge this to master before I can test it out.
> Initial BSI update workflow

- package-lock.json
https://github.com/Brightspace/d2l-rubric/pull/689
> Bump d2l-rubric 20.20.10

- .github/workflows/bsi-update.yml
I thought this was optional but it is not
> Add git config info

- .github/workflows/bsi-update.yml
> Auto BSI - Set upstream

- .github/workflows/bsi-update.yml
Branch is getting there now but doesn't look how I'd expect - need to clear `package-lock.json` (and `node_modules`, only the second time we run it since it shouldn't start with anything).
The PR is also not getting created but the step doesn't fail, so trying to get more info there.
> Clear package-lock and node_modules

- .github/workflows/bsi-update.yml
Was not properly filtering out PRs to look for ones from `ghworkflow/bsi_auto_update` only - needed to add the org
> Auto BSI - Fix call to list PRs

- .github/workflows/bsi-update.yml
It was making a new branch every time, meaning it couldn't properly determine whether it needed to apply a new commit with additional changes or not.  This will hopefully fix it!
> Try to fetch the branch before checking it out

- .github/workflows/bsi-update.yml
- README.md
Scheduled every hour for now, at *:30.  Tried to pick a time that works well for KW + Vancouver + Standard time + Daylight savings time.
> Schedule BSI Update Workflow

- web-components/d2l-content-creation.js
**NOTE:** Don't merge until new activities component gets in.
> Switch the component that renders FACE content creation UI

- package-lock.json
See BrightspaceUI/core#875 and Brightspace/lms#1736 (files)
> Version bump core for OSLO cert fix

- web-components/bsi-unbundled.js
> unbundling dropdown components

- web-components/bsi-unbundled.js
> unbundling icons

- .github/workflows/bsi-update-merge.yml
It's not merging the PR, so trying to get more info on why
> Auto Merge - Remove unused variable and add debugging

- .github/workflows/bsi-update-merge.yml
Going to try adding the retry back in - I think I misunderstood its purpose when reading the docs.
> Auto Merge - Try adding retries back

- .github/workflows/bsi-update-merge.yml
I have a feeling it might be the manual dispatch that's the problem... we'll see!
> Auto Merge - Try retries and schedule

- .github/workflows/bsi-update-merge.yml
Adding the schedule back in, removing the debugging, and adjusting some variables a bit.
> US121650 - Add schedule back

- .github/workflows/bsi-update.yml
I figured `undefined` would be counted as a failure for the step's `if`, but it is trying to run the approval with an `undefined` PR id.
> US121650 - Fix Approval step if check

- .github/workflows/bsi-update.yml
This is me guessing at this point...
> US121650 - Try again to fix approve

- .github/workflows/bsi-update.yml
> [skip ci] Try without quotes

- .github/workflows/bsi-update.yml
That last thing did not work at all... let's try this
> US121650 - New strategy to getting the approve step only running when needed

- .github/workflows/bsi-update.yml
> [skip ci] Another attempt at running approval only when we have to

- .github/workflows/bsi-merge.yml
- .github/workflows/bsi-update.yml
- README.md
I think this is the last of it! 🤞 
Fixing the approval token, and and changing the action name so the filtering works better.
> US121650 - Fix approve token and rearrange

- package-lock.json
- rollup/rollup-wc.config.js
Moved activity editor to appFiles. I am assuming this means it will only be loaded for the page that uses it?
> Change to d2l-hc-activity-editor and move to appFiles.

- package-lock.json
> upgrading to 1.85.5 of core

- package-lock.json
> engagement dashboard bump for 20.10.11 fixes

- package-lock.json
https://github.com/Brightspace/outcomes-level-of-achievement-ui/pull/62
> Bump outcomes-level-of-achievement 20.20.12

- package-lock.json
- package.json
This includes all the changes to get BSI working again with the 1.0.1 version of pagination.
I'm pointing discovery-fra at a temporary branch that includes only this change on top of the existing version that was in BSI, as their team is mostly away today and figuring out how to do a proper release was going to be complicated.
> Upgrade pagination

- package-lock.json
Consistent Eval Visual Diff Test Changes
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/182
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/184
Outcomes Mastery View Changes
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/183
https://github.com/Brightspace/outcomes-level-of-achievement-ui/pull/65
https://github.com/Brightspace/d2l-outcomes-overall-achievement/pull/61
> Cert fixes for Outcomes Mastery View

- rollup/rollup-wc.config.js
- web-components/d2l-work-to-do-widget.js
> Add work to do widget

- .serge-mapping.json
As I understand it, the BSI build will read this file, follow it to our .serge.json, then package our langterms; then the LMS build will get that package and include it in the language manager.
FYI @anhill-D2L @MykolaGalian @NicholasHallman @rohitvinnakota
> US118253: add engagement dashboard to oslo

- rollup/rollup-wc.config.js
- web-components/d2l-quick-eval-widget.js
As per https://github.com/Brightspace/brightspace-integration/pull/2943#issuecomment-741983637
> Dont use web-components, reference node_modules directly, this is the way

- rollup/rollup-wc.config.js
Add d2l-consistent-evaluation-popup-rubric
> Add rubric popup for consistent-evaluation

- package-lock.json
Cert fix for [DE41517](https://rally1.rallydev.com/#/57732444928d/custom/373260458992?detail=%2Fdefect%2F459580933384)
> Bump outcomes-level-of-achievement-ui

- package-lock.json
Updates to d2l-engagement-dashboard 1.2101.5 which includes translations.
> insights-engagement-dashboard 20.21.1 with translations

- .serge-mapping.json
- package-lock.json
Adding foundation-components to allow localization through serge.
> Add foundation components to serge mapping

- package-lock.json
https://rally1.rallydev.com/#/29180338367d/iterationstatus?detail=/defect/484000087392
Bumping version of d2l-activities for a cert fix.
> Manual version bump for cert fix

- package-lock.json
Fixed defect: DE42103, DE42064, DE42161, DE42162, DE42120, DE42114, DE42099, DE4211, DE42104, DE42101
> [Cert Fix 20.21.2] - defects fixes for learning path

- package-lock.json
fix defects: DE42117, DE42143, DE42098, DE42145, DE42190
> [Cert Fix 20.21.2] use list-item-accumulator version 1.1.4

- package-lock.json
fixed: DE42228, DE420984, DE42126, DE42282
> [Cert Fix 20.21.2] fix learning path defects

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/activities/commit/efa699705680efb46f8c5889c58f439808f9d2fa
> Backport translations

- package-lock.json
Also updates pagination because of a translation hiccup (https://github.com/BrightspaceUILabs/pagination/pull/27)
> insights-engagement-dashboard 20.21.2 with translations

- package-lock.json
> [Cert Fix 20.21.2] translations for hmc foundation-components

- package-lock.json
Not merging just yet because of some coordination needed on the actual release but getting a PR up and ready.
> [20.21.2 hotfix] bump core: fix dropdown position

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/activities/commit/8a7461dfb0d2a9d0162918e68ead129d7ccdd18f
> Bump d2l-activities

- package-lock.json
Bump to include translation updates https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/330
> Bump Consistent-Eval

- rollup/rollup-wc.config.js
[US123769](https://rally1.rallydev.com/#/357252275780d/custom/367300408400?detail=%2Fuserstory%2F480099321508&fdp=true&fdp=true?fdp=true)
Adding a sample component for use with a legacy page.
This component will be replaced with the real one once the MVC and Legacy adapters have been created and are functional.
> Adding a sample foundations component to rollup

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/siren-sdk/releases/tag/v1.44.2
> CERT: DE42885 - Lessons FACE > Due dates and Availability dates are broken

- .serge-mapping.json
Adding d2l-cpd serge mapping file as instructed by OSLO documentation [here](https://docs.dev.d2l/index.php/Oslo#Include_your_web_component_within_the_BSI_project).
> Add d2l-cpd to serge mapping file for OSLO integration`

- package-lock.json
This is for cert in `20.21.4`.
> upgrading core to 1.118.3 to pick up menu fix

- rollup/rollup-wc.config.js
> fix: Work To Do

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/activities/releases/tag/v3.137.1
> DE42834 Bump d2l-activities

- package-lock.json
Uses this release
https://github.com/Brightspace/d2l-activity-alignments/releases/tag/v2.1.5
> Bump d2l-activity-alignments for translations

- package-lock.json
Updates translations for `d2l-rubrics` and `d2l-outcomes-overall-achievement`.
> Translation fixes (20.21.4)

- package-lock.json
Required to get this fix in: https://github.com/BrightspaceUI/htmleditor/pull/159
Over-under on how many of these I'm going to need to do? Sigh.
> DE43156 - Update HTML editor to v1.5.3

- package-lock.json
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fdefect%2F601522470508&expandApp=486232622048&fdp=true?fdp=true
> [20.21.5] Update activities for DE43326 fix

- package-lock.json
https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fdefect%2F600538373508
> Bump activites for DE43255

- package-lock.json
Add cert fixes for work to do.
> Cert for work to do

- package-lock.json
- package.json
[US127858](https://rally1.rallydev.com/#/23525809118d/portfolioitemstreegrid?detail=%2Fuserstory%2F603047932448&fdp=true?fdp=true): [AQ] New Temporary Assessment Quality Dashboard Page
PR adds `Assessment Quality Dashboard Page` package to BSI
FYI @anhill-D2L @hyehayes @johngwilkinson @NicholasHallman @bemailloux
> US127858 [AQ] New Temporary Assessment Quality Dashboard Page

- .serge-mapping.json
- package-lock.json
- package.json
- rollup/rollup-wc.config.js
Part of https://rally1.rallydev.com/#/431372673576d/iterationstatus?detail=%2Fuserstory%2F519546414124&fdp=true?fdp=true
> US126758 - Add custom early progress report app

- .travis.yml
Upgrade to Node version 14 to see if it solves the memory issues during bulds.
> Upgrading to Node 14 in CI

- package-lock.json
- package.json
Contains the following changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.11.0...v1.11.1
> Bump HTML editor version to 1.11.1

- package-lock.json
```Context```
translations for list-item-accumulator
```Quality```
tested locally, deleted node_modules and ran npm ci
afterwards, list-item-accumulator in node_modules contained the lang files.
> list item accumulator translations

- package-lock.json
[US126676](https://rally1.rallydev.com/#/357252966636d/custom/367300408400?detail=%2Fuserstory%2F519023869316
)
updating foundation-components with translations commit
> Cert foundation component translations

- .serge-mapping.json
Associated Rally ticket: https://rally1.rallydev.com/#/24745451007/custom/24747457579?detail=%2Fuserstory%2F519797613000
This is necessary as per the docs: https://docs.dev.d2l/index.php/Oslo#Include_your_web_component_within_the_BSI_project
> US126879 - Add HtmlEditor serge mapping to BSI

- package-lock.json
Adds statistics button to inline experience - https://github.com/Brightspace/d2l-rubric/pull/793
> [20.21.7] Bump d2l-rubric

- package-lock.json
These changes are for a certfix to allow auto-loading of images, after the behaviour was broken by changing the wrappers from simple-overlay to d2l-dialog-fullscreen.
> Certfix image-banner-overlay and my-courses

- package-lock.json
This is the hotfix version of this for 20.21.6.
> intl 3.5.1 picks up Safari fix

- package-lock.json
Cert fix discover for course URL caching change
> Updated discover version

- package-lock.json
[DE44014](https://rally1.rallydev.com/#/29180338367d/custom/486232622040?detail=%2Fdefect%2F601875494967%2Ftasks&fdp=true&fdp=true?fdp=true): [cert][Android] FACE Assignment > RHP Accordions cannot open on Android devices
> DE44014 [cert][Android] FACE Assignment > RHP Accordions cannot open on Android devices

- package-lock.json
Bring in fr-on translations in this PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/1855
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fdefect%2F602874398299&fdp=true?fdp=true
> Bumping 20.21.7 activities version

- package-lock.json
Backporting [this update in CE](https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/583) with [these changes from the Profile Card](https://github.com/BrightspaceUILabs/user-profile-card/commit/593c6ce90b77ef9915d90a1b28ae9561bc55bc61)
> Bump profile card and ConsistentEval

- es-dev-server-dev.config.js
Prod builds are fine, but dev was mixing the fix.
> Fix UMD timebomb caused by the focus-visible polyfill

- .serge-mapping.json
- package-lock.json
- package.json
- rollup/rollup-wc.config.js
https://rally1.rallydev.com/#/431372673576d/dashboard?detail=%2Fuserstory%2F603812555239
> US129882 - Copy Assignment to other Courses BSI map

- package-lock.json
Fixes issues with criterion score overrides not showing up.
> DE44492/DE44409 - Rubric fixes

- package-lock.json
See [original PR](https://github.com/BrightspaceHypermediaComponents/foundation-components/pull/272)
> DE44196 Fix due date being cut off

- package-lock.json
See [original](https://github.com/BrightspaceHypermediaComponents/foundation-components/pull/272)
> DE44196 Fix due date being cut off backport

- docs/web-components.md
Troubleshooting notes on addding BSI module to project.
> Adding Troubleshooting Section

- package-lock.json
Bug fixes https://github.com/Brightspace/d2l-rubric/pull/922.
> Update `d2l-rubrics` (20.21.7)

- package-lock.json
> Update `d2l-rubric` (20.21.8/cert)

- package-lock.json
Brings in lang terms in this activities PR: https://github.com/BrightspaceHypermediaComponents/activities/pull/1908
https://rally1.rallydev.com/#/29180338367d/dashboard?detail=%2Fdefect%2F604753981939&fdp=true?fdp=true
> DE44483 Bumped activities version

- package-lock.json
- package.json
Hotfix for: https://github.com/Brightspace/d2l-rubric/pull/933
Rally ticket: https://rally1.rallydev.com/#/57732444928ud/custom/373260458992?detail=%2Fdefect%2F605369054319
> Update d2l-rubric version for DE44584 hotfix

- .github/workflows/ci.yml
- package-lock.json
- package.json
- rollup/rollup-wc.config.js
[US127919](https://rally1.rallydev.com/#/431372673576d/iterationstatus?detail=%2Fuserstory%2F603444721280&fdp=true?fdp=true)
https://github.com/BrightspaceUILabs/input-duration
> Add input-duration component to rollup

- rollup/rollup-wc.config.js
[US120605](https://rally1.rallydev.com/#/431372673576d/iterationstatus?detail=%2Fuserstory%2F436329310560)
https://github.com/BrightspaceUILabs/role-selector
> Adding role-selector component rollup

- package-lock.json
- package.json
Bumping consistent-eval & user-profile-card to fix [DE44613](https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fdefect%2F605473382495)
> Bump consistent-eval and user-profile-card

- package-lock.json
- package.json
backport user-profile-card orgDefinedID to 20.21.7
> bump ce and user-profile-card

- package-lock.json
Contains these changes: https://github.com/BrightspaceUI/htmleditor/compare/v1.20.8...v1.20.9
> Bump editor version to 1.20.9

- package-lock.json
bump consistent-evaluation to fix zero rubric issue 
Story: [DE43579](https://rally1.rallydev.com/#/42960320374d/custom/236803223728?detail=%2Fdefect%2F604817053676)
> bump consistent-evaluation

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/commit/3482ecbc7f0ac4bf4c5065868023935293e8e77a
> bump ce version

- package-lock.json
https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/commit/698ed99717ab55dea6dbf5bec55a3563f7ad02f0
> Update CE to 1.311.6

- package-lock.json
Version 205 accidentally made it in before 20.22.1 branching.
> Lower core version to 1.204.0 in 20.21.12

- web-components/d2l-html-block.js
Aligns with this PR: https://github.com/BrightspaceUI/core/pull/1824
> Align html-block renderers with new format

- package-lock.json
https://rally1.rallydev.com/#/?detail=/defect/616923363785&fdp=true
> DE46157 hotfix

- package-lock.json
https://rally1.rallydev.com/#/?detail=/defect/616921131105&fdp=true
> fix: DE46156 certfix

- .serge-mapping.json
[US123325](https://rally1.rallydev.com/#/?detail=/userstory/464450996060&fdp=true)
> add discover to serge mapping for oslo

- package-lock.json
- package.json
[US130935](https://rally1.rallydev.com/#/?detail=/userstory/606865866871&fdp=true)
To include the changes from https://github.com/Brightspace/continuous-professional-development/pull/367
> US130935 - Update CPD to version 3
